# ==============================================================
# File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
# Version: 2016.4
# Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
# 
# ==============================================================

proc sc_sim_check {ret err logfile} {
	if {$::AESL_AUTOSIM::gDebug == 1} {
		puts stdout "[debug_prompt arg check_sim.tcl] start...";
	}
    set errfile "err.log"
    if {[file exists $errfile] && [file size $errfile] != 0} {
        set fl [open $errfile r]
        while {[gets $fl line] >= 0} {
            if {[string first "AESL_mErrNo = " $line] == 0} {
                set mismatch_num [string range $line [string length "AESL_mErrNo = "] end]
                if {$mismatch_num != 0} {
                    ap_puts_err "COSIM" 403 "SystemC simulation FAILED with ${mismatch_num} mismatches detected."
                    break
                }
            }
        }
    }
    if {$ret || $err != ""} {
        if { [lindex $::errorCode 0] eq "CHILDSTATUS"} {
            set status [lindex $::errorCode 2]
            if {$status != ""} {
                ap_puts_err "COSIM" 404 "Simulation failed: Function \'main\' returns nonzero value \'$status\'."
            } else {
                ap_puts_err "COSIM" 405 "Simulation failed."
            }
        } else {
            ap_puts_err "COSIM" 405 "Simulation failed."
        }
    }
    if {[file exists $logfile]} {
        set cmdret [catch {eval exec "grep \"Error:\" $logfile"} err]
        file delete -force $logfile
        if {$cmdret == 0} {
            ap_puts_err "COSIM" 405 "Simulation failed."
        }
    }
	if {$::AESL_AUTOSIM::gDebug == 1} {
		puts stdout "[debug_prompt arg check_sim.tcl] finish...";
	}
}

proc rtl_sim_check {} {
	if {$::AESL_AUTOSIM::gDebug == 1} {
		puts stdout "[debug_prompt arg check_sim.tcl] start...";
	}
    set errfile "err.log"
    if {[file exists $errfile] && [file size $errfile] != 0} {
        set fl [open $errfile r]
        set unmatch_num 0
        while {[gets $fl line] >= 0} {
            if {[string first "unmatched" $line] != -1} {
                set unmatch_num [expr $unmatch_num + 1]
            }
        }
        if {$unmatch_num != 0} {
            ap_puts_err "COSIM" 406 "Simulation FAILED with ${unmatch_num} mismatches detected."
        }
    }
    if {[file exists ".aesl_error"]} {
        set errfl [open ".aesl_error" r]
        gets $errfl line
        if {$line != 0} {
            ap_puts_err "COSIM" 407 "Simulation failed: Function \'main\' returns nonzero value \'$line\'."
        }
    }
    if {[file exists ".exit.err"]} {
        ap_puts_err "COSIM" 405 "Simulation failed."
    }
	if {$::AESL_AUTOSIM::gDebug == 1} {
		puts stdout "[debug_prompt arg check_sim.tcl] finish...";
	}
}

proc check_tvin_file {} {
	if {$::AESL_AUTOSIM::gDebug == 1} {
		puts stdout "[debug_prompt arg check_sim.tcl] start...";
	}
    set rtlfilelist {
         "c.TowerPeaks.autotvin_towerET_0_0.dat"
         "c.TowerPeaks.autotvin_towerET_0_1.dat"
         "c.TowerPeaks.autotvin_towerET_0_2.dat"
         "c.TowerPeaks.autotvin_towerET_0_3.dat"
         "c.TowerPeaks.autotvin_towerET_1_0.dat"
         "c.TowerPeaks.autotvin_towerET_1_1.dat"
         "c.TowerPeaks.autotvin_towerET_1_2.dat"
         "c.TowerPeaks.autotvin_towerET_1_3.dat"
         "c.TowerPeaks.autotvin_towerET_2_0.dat"
         "c.TowerPeaks.autotvin_towerET_2_1.dat"
         "c.TowerPeaks.autotvin_towerET_2_2.dat"
         "c.TowerPeaks.autotvin_towerET_2_3.dat"
         "c.TowerPeaks.autotvin_towerET_3_0.dat"
         "c.TowerPeaks.autotvin_towerET_3_1.dat"
         "c.TowerPeaks.autotvin_towerET_3_2.dat"
         "c.TowerPeaks.autotvin_towerET_3_3.dat"
         "c.TowerPeaks.autotvin_towerET_4_0.dat"
         "c.TowerPeaks.autotvin_towerET_4_1.dat"
         "c.TowerPeaks.autotvin_towerET_4_2.dat"
         "c.TowerPeaks.autotvin_towerET_4_3.dat"
         "c.TowerPeaks.autotvin_towerET_5_0.dat"
         "c.TowerPeaks.autotvin_towerET_5_1.dat"
         "c.TowerPeaks.autotvin_towerET_5_2.dat"
         "c.TowerPeaks.autotvin_towerET_5_3.dat"
         "c.TowerPeaks.autotvin_towerET_6_0.dat"
         "c.TowerPeaks.autotvin_towerET_6_1.dat"
         "c.TowerPeaks.autotvin_towerET_6_2.dat"
         "c.TowerPeaks.autotvin_towerET_6_3.dat"
         "c.TowerPeaks.autotvin_towerET_7_0.dat"
         "c.TowerPeaks.autotvin_towerET_7_1.dat"
         "c.TowerPeaks.autotvin_towerET_7_2.dat"
         "c.TowerPeaks.autotvin_towerET_7_3.dat"
         "c.TowerPeaks.autotvin_towerET_8_0.dat"
         "c.TowerPeaks.autotvin_towerET_8_1.dat"
         "c.TowerPeaks.autotvin_towerET_8_2.dat"
         "c.TowerPeaks.autotvin_towerET_8_3.dat"
         "c.TowerPeaks.autotvin_towerET_9_0.dat"
         "c.TowerPeaks.autotvin_towerET_9_1.dat"
         "c.TowerPeaks.autotvin_towerET_9_2.dat"
         "c.TowerPeaks.autotvin_towerET_9_3.dat"
         "c.TowerPeaks.autotvin_towerET_10_0.dat"
         "c.TowerPeaks.autotvin_towerET_10_1.dat"
         "c.TowerPeaks.autotvin_towerET_10_2.dat"
         "c.TowerPeaks.autotvin_towerET_10_3.dat"
         "c.TowerPeaks.autotvin_towerET_11_0.dat"
         "c.TowerPeaks.autotvin_towerET_11_1.dat"
         "c.TowerPeaks.autotvin_towerET_11_2.dat"
         "c.TowerPeaks.autotvin_towerET_11_3.dat"
         "c.TowerPeaks.autotvin_towerET_12_0.dat"
         "c.TowerPeaks.autotvin_towerET_12_1.dat"
         "c.TowerPeaks.autotvin_towerET_12_2.dat"
         "c.TowerPeaks.autotvin_towerET_12_3.dat"
         "c.TowerPeaks.autotvin_towerET_13_0.dat"
         "c.TowerPeaks.autotvin_towerET_13_1.dat"
         "c.TowerPeaks.autotvin_towerET_13_2.dat"
         "c.TowerPeaks.autotvin_towerET_13_3.dat"
         "c.TowerPeaks.autotvin_towerET_14_0.dat"
         "c.TowerPeaks.autotvin_towerET_14_1.dat"
         "c.TowerPeaks.autotvin_towerET_14_2.dat"
         "c.TowerPeaks.autotvin_towerET_14_3.dat"
         "c.TowerPeaks.autotvin_towerET_15_0.dat"
         "c.TowerPeaks.autotvin_towerET_15_1.dat"
         "c.TowerPeaks.autotvin_towerET_15_2.dat"
         "c.TowerPeaks.autotvin_towerET_15_3.dat"
         "c.TowerPeaks.autotvin_towerET_16_0.dat"
         "c.TowerPeaks.autotvin_towerET_16_1.dat"
         "c.TowerPeaks.autotvin_towerET_16_2.dat"
         "c.TowerPeaks.autotvin_towerET_16_3.dat"
         "c.TowerPeaks.autotvout_TowerPhi_0.dat"
         "c.TowerPeaks.autotvout_TowerPhi_1.dat"
         "c.TowerPeaks.autotvout_TowerPhi_2.dat"
         "c.TowerPeaks.autotvout_TowerPhi_3.dat"
         "c.TowerPeaks.autotvout_TowerPhi_4.dat"
         "c.TowerPeaks.autotvout_TowerPhi_5.dat"
         "c.TowerPeaks.autotvout_TowerPhi_6.dat"
         "c.TowerPeaks.autotvout_TowerPhi_7.dat"
         "c.TowerPeaks.autotvout_TowerPhi_8.dat"
         "c.TowerPeaks.autotvout_TowerPhi_9.dat"
         "c.TowerPeaks.autotvout_TowerPhi_10.dat"
         "c.TowerPeaks.autotvout_TowerPhi_11.dat"
         "c.TowerPeaks.autotvout_TowerPhi_12.dat"
         "c.TowerPeaks.autotvout_TowerPhi_13.dat"
         "c.TowerPeaks.autotvout_TowerPhi_14.dat"
         "c.TowerPeaks.autotvout_TowerPhi_15.dat"
         "c.TowerPeaks.autotvout_TowerPhi_16.dat"
         "c.TowerPeaks.autotvout_TowerPhi_17.dat"
         "c.TowerPeaks.autotvout_TowerPhi_18.dat"
         "c.TowerPeaks.autotvout_TowerPhi_19.dat"
         "c.TowerPeaks.autotvout_TowerPhi_20.dat"
         "c.TowerPeaks.autotvout_TowerPhi_21.dat"
         "c.TowerPeaks.autotvout_TowerPhi_22.dat"
         "c.TowerPeaks.autotvout_TowerPhi_23.dat"
         "c.TowerPeaks.autotvout_TowerPhi_24.dat"
         "c.TowerPeaks.autotvout_TowerPhi_25.dat"
         "c.TowerPeaks.autotvout_TowerPhi_26.dat"
         "c.TowerPeaks.autotvout_TowerPhi_27.dat"
         "c.TowerPeaks.autotvout_TowerPhi_28.dat"
         "c.TowerPeaks.autotvout_TowerPhi_29.dat"
         "c.TowerPeaks.autotvout_TowerEta_0.dat"
         "c.TowerPeaks.autotvout_TowerEta_1.dat"
         "c.TowerPeaks.autotvout_TowerEta_2.dat"
         "c.TowerPeaks.autotvout_TowerEta_3.dat"
         "c.TowerPeaks.autotvout_TowerEta_4.dat"
         "c.TowerPeaks.autotvout_TowerEta_5.dat"
         "c.TowerPeaks.autotvout_TowerEta_6.dat"
         "c.TowerPeaks.autotvout_TowerEta_7.dat"
         "c.TowerPeaks.autotvout_TowerEta_8.dat"
         "c.TowerPeaks.autotvout_TowerEta_9.dat"
         "c.TowerPeaks.autotvout_TowerEta_10.dat"
         "c.TowerPeaks.autotvout_TowerEta_11.dat"
         "c.TowerPeaks.autotvout_TowerEta_12.dat"
         "c.TowerPeaks.autotvout_TowerEta_13.dat"
         "c.TowerPeaks.autotvout_TowerEta_14.dat"
         "c.TowerPeaks.autotvout_TowerEta_15.dat"
         "c.TowerPeaks.autotvout_TowerEta_16.dat"
         "c.TowerPeaks.autotvout_TowerEta_17.dat"
         "c.TowerPeaks.autotvout_TowerEta_18.dat"
         "c.TowerPeaks.autotvout_TowerEta_19.dat"
         "c.TowerPeaks.autotvout_TowerEta_20.dat"
         "c.TowerPeaks.autotvout_TowerEta_21.dat"
         "c.TowerPeaks.autotvout_TowerEta_22.dat"
         "c.TowerPeaks.autotvout_TowerEta_23.dat"
         "c.TowerPeaks.autotvout_TowerEta_24.dat"
         "c.TowerPeaks.autotvout_TowerEta_25.dat"
         "c.TowerPeaks.autotvout_TowerEta_26.dat"
         "c.TowerPeaks.autotvout_TowerEta_27.dat"
         "c.TowerPeaks.autotvout_TowerEta_28.dat"
         "c.TowerPeaks.autotvout_TowerEta_29.dat"
    }
    foreach rtlfile $rtlfilelist {
        if {[file isfile $rtlfile]} {
        } else {
            ap_puts_err "COSIM" 320 "C TB testing failed. Please check C TB or re-run cosim.  "
            return 1
        }
        set ret [catch {eval exec "grep /runtime $rtlfile"} err]
        if { $ret } {
            ap_puts_err "COSIM" 320 "C TB testing failed. Please check C TB or re-run cosim.  "
            return 1
        }
    }
	if {$::AESL_AUTOSIM::gDebug == 1} {
		puts stdout "[debug_prompt arg check_sim.tcl] finish...";
	}
    return 0
}

proc check_tvout_file {} {
	if {$::AESL_AUTOSIM::gDebug == 1} {
		puts stdout "[debug_prompt arg check_sim.tcl] start...";
	}
    set rtlfilelist {
         "rtl.TowerPeaks.autotvout_TowerPhi_0.dat"
         "rtl.TowerPeaks.autotvout_TowerPhi_1.dat"
         "rtl.TowerPeaks.autotvout_TowerPhi_2.dat"
         "rtl.TowerPeaks.autotvout_TowerPhi_3.dat"
         "rtl.TowerPeaks.autotvout_TowerPhi_4.dat"
         "rtl.TowerPeaks.autotvout_TowerPhi_5.dat"
         "rtl.TowerPeaks.autotvout_TowerPhi_6.dat"
         "rtl.TowerPeaks.autotvout_TowerPhi_7.dat"
         "rtl.TowerPeaks.autotvout_TowerPhi_8.dat"
         "rtl.TowerPeaks.autotvout_TowerPhi_9.dat"
         "rtl.TowerPeaks.autotvout_TowerPhi_10.dat"
         "rtl.TowerPeaks.autotvout_TowerPhi_11.dat"
         "rtl.TowerPeaks.autotvout_TowerPhi_12.dat"
         "rtl.TowerPeaks.autotvout_TowerPhi_13.dat"
         "rtl.TowerPeaks.autotvout_TowerPhi_14.dat"
         "rtl.TowerPeaks.autotvout_TowerPhi_15.dat"
         "rtl.TowerPeaks.autotvout_TowerPhi_16.dat"
         "rtl.TowerPeaks.autotvout_TowerPhi_17.dat"
         "rtl.TowerPeaks.autotvout_TowerPhi_18.dat"
         "rtl.TowerPeaks.autotvout_TowerPhi_19.dat"
         "rtl.TowerPeaks.autotvout_TowerPhi_20.dat"
         "rtl.TowerPeaks.autotvout_TowerPhi_21.dat"
         "rtl.TowerPeaks.autotvout_TowerPhi_22.dat"
         "rtl.TowerPeaks.autotvout_TowerPhi_23.dat"
         "rtl.TowerPeaks.autotvout_TowerPhi_24.dat"
         "rtl.TowerPeaks.autotvout_TowerPhi_25.dat"
         "rtl.TowerPeaks.autotvout_TowerPhi_26.dat"
         "rtl.TowerPeaks.autotvout_TowerPhi_27.dat"
         "rtl.TowerPeaks.autotvout_TowerPhi_28.dat"
         "rtl.TowerPeaks.autotvout_TowerPhi_29.dat"
         "rtl.TowerPeaks.autotvout_TowerEta_0.dat"
         "rtl.TowerPeaks.autotvout_TowerEta_1.dat"
         "rtl.TowerPeaks.autotvout_TowerEta_2.dat"
         "rtl.TowerPeaks.autotvout_TowerEta_3.dat"
         "rtl.TowerPeaks.autotvout_TowerEta_4.dat"
         "rtl.TowerPeaks.autotvout_TowerEta_5.dat"
         "rtl.TowerPeaks.autotvout_TowerEta_6.dat"
         "rtl.TowerPeaks.autotvout_TowerEta_7.dat"
         "rtl.TowerPeaks.autotvout_TowerEta_8.dat"
         "rtl.TowerPeaks.autotvout_TowerEta_9.dat"
         "rtl.TowerPeaks.autotvout_TowerEta_10.dat"
         "rtl.TowerPeaks.autotvout_TowerEta_11.dat"
         "rtl.TowerPeaks.autotvout_TowerEta_12.dat"
         "rtl.TowerPeaks.autotvout_TowerEta_13.dat"
         "rtl.TowerPeaks.autotvout_TowerEta_14.dat"
         "rtl.TowerPeaks.autotvout_TowerEta_15.dat"
         "rtl.TowerPeaks.autotvout_TowerEta_16.dat"
         "rtl.TowerPeaks.autotvout_TowerEta_17.dat"
         "rtl.TowerPeaks.autotvout_TowerEta_18.dat"
         "rtl.TowerPeaks.autotvout_TowerEta_19.dat"
         "rtl.TowerPeaks.autotvout_TowerEta_20.dat"
         "rtl.TowerPeaks.autotvout_TowerEta_21.dat"
         "rtl.TowerPeaks.autotvout_TowerEta_22.dat"
         "rtl.TowerPeaks.autotvout_TowerEta_23.dat"
         "rtl.TowerPeaks.autotvout_TowerEta_24.dat"
         "rtl.TowerPeaks.autotvout_TowerEta_25.dat"
         "rtl.TowerPeaks.autotvout_TowerEta_26.dat"
         "rtl.TowerPeaks.autotvout_TowerEta_27.dat"
         "rtl.TowerPeaks.autotvout_TowerEta_28.dat"
         "rtl.TowerPeaks.autotvout_TowerEta_29.dat"
    }
    foreach rtlfile $rtlfilelist {
        if {[file isfile $rtlfile]} {
        } else {
            ap_puts_err "COSIM" 303 "Aborting co-simulation: RTL simulation failed.  "
            return 1
        }
        set ret [catch {eval exec "grep /runtime $rtlfile"} err]
        if { $ret } {
            ap_puts_err "COSIM" 303 "Aborting co-simulation: RTL simulation failed.  "
            return 1
        }
    }
	if {$::AESL_AUTOSIM::gDebug == 1} {
		puts stdout "[debug_prompt arg check_sim.tcl] finish...";
	}
    return 0
}
