// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module bitonic_1_8 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        Cluster_1_Deposits_0,
        Cluster_1_Deposits_1,
        Cluster_1_Deposits_2,
        Cluster_1_Deposits_3,
        Cluster_1_Deposits_4,
        Cluster_1_Deposits_5,
        Cluster_1_Deposits_6,
        Cluster_1_Deposits_7,
        Cluster_1_Deposits_8,
        Cluster_1_Deposits_9,
        Cluster_1_Deposits_1_3,
        Cluster_1_Deposits_1_4,
        Cluster_1_Eta_0_rea,
        Cluster_1_Eta_1_rea,
        Cluster_1_Eta_2_rea,
        Cluster_1_Eta_3_rea,
        Cluster_1_Eta_4_rea,
        Cluster_1_Eta_5_rea,
        Cluster_1_Eta_6_rea,
        Cluster_1_Eta_7_rea,
        Cluster_1_Eta_8_rea,
        Cluster_1_Eta_9_rea,
        Cluster_1_Eta_10_re,
        Cluster_1_Eta_11_re,
        Cluster_1_Phi_0_rea,
        Cluster_1_Phi_1_rea,
        Cluster_1_Phi_2_rea,
        Cluster_1_Phi_3_rea,
        Cluster_1_Phi_4_rea,
        Cluster_1_Phi_5_rea,
        Cluster_1_Phi_6_rea,
        Cluster_1_Phi_7_rea,
        Cluster_1_Phi_8_rea,
        Cluster_1_Phi_9_rea,
        Cluster_1_Phi_10_re,
        Cluster_1_Phi_11_re,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9,
        ap_ce
);

parameter    ap_ST_fsm_state1 = 2'b1;
parameter    ap_ST_fsm_state2 = 2'b10;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv16_0 = 16'b0000000000000000;
parameter    ap_const_lv2_0 = 2'b00;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] Cluster_1_Deposits_0;
input  [15:0] Cluster_1_Deposits_1;
input  [15:0] Cluster_1_Deposits_2;
input  [15:0] Cluster_1_Deposits_3;
input  [15:0] Cluster_1_Deposits_4;
input  [15:0] Cluster_1_Deposits_5;
input  [15:0] Cluster_1_Deposits_6;
input  [15:0] Cluster_1_Deposits_7;
input  [15:0] Cluster_1_Deposits_8;
input  [15:0] Cluster_1_Deposits_9;
input  [15:0] Cluster_1_Deposits_1_3;
input  [15:0] Cluster_1_Deposits_1_4;
input  [1:0] Cluster_1_Eta_0_rea;
input  [1:0] Cluster_1_Eta_1_rea;
input  [1:0] Cluster_1_Eta_2_rea;
input  [1:0] Cluster_1_Eta_3_rea;
input  [1:0] Cluster_1_Eta_4_rea;
input  [1:0] Cluster_1_Eta_5_rea;
input  [1:0] Cluster_1_Eta_6_rea;
input  [1:0] Cluster_1_Eta_7_rea;
input  [1:0] Cluster_1_Eta_8_rea;
input  [1:0] Cluster_1_Eta_9_rea;
input  [1:0] Cluster_1_Eta_10_re;
input  [1:0] Cluster_1_Eta_11_re;
input  [0:0] Cluster_1_Phi_0_rea;
input  [0:0] Cluster_1_Phi_1_rea;
input  [0:0] Cluster_1_Phi_2_rea;
input  [0:0] Cluster_1_Phi_3_rea;
input  [1:0] Cluster_1_Phi_4_rea;
input  [1:0] Cluster_1_Phi_5_rea;
input  [1:0] Cluster_1_Phi_6_rea;
input  [1:0] Cluster_1_Phi_7_rea;
input  [1:0] Cluster_1_Phi_8_rea;
input  [1:0] Cluster_1_Phi_9_rea;
input  [1:0] Cluster_1_Phi_10_re;
input  [1:0] Cluster_1_Phi_11_re;
output  [15:0] ap_return_0;
output  [15:0] ap_return_1;
output  [15:0] ap_return_2;
output  [15:0] ap_return_3;
output  [15:0] ap_return_4;
output  [15:0] ap_return_5;
output  [15:0] ap_return_6;
output  [15:0] ap_return_7;
output  [15:0] ap_return_8;
output  [15:0] ap_return_9;
input   ap_ce;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire   [0:0] ap_CS_fsm_state1;
wire   [15:0] Cluster_1_Deposits12_2_fu_990_p3;
reg   [15:0] Cluster_1_Deposits12_2_reg_1308;
wire   [15:0] Cluster_1_Deposits_1_8_fu_998_p3;
reg   [15:0] Cluster_1_Deposits_1_8_reg_1313;
wire   [1:0] Cluster_1_Eta16_1_Cl_fu_1006_p3;
reg   [1:0] Cluster_1_Eta16_1_Cl_reg_1318;
wire   [1:0] Cluster_1_Eta_1_Clus_fu_1014_p3;
reg   [1:0] Cluster_1_Eta_1_Clus_reg_1323;
wire   [1:0] Cluster_1_Phi31_1_Cl_fu_1022_p3;
reg   [1:0] Cluster_1_Phi31_1_Cl_reg_1328;
wire   [1:0] Cluster_1_Phi_1_Clus_fu_1030_p3;
reg   [1:0] Cluster_1_Phi_1_Clus_reg_1333;
wire   [15:0] Cluster_1_Deposits3_1_fu_1044_p3;
reg   [15:0] Cluster_1_Deposits3_1_reg_1338;
wire   [15:0] Cluster_1_Deposits2_1_fu_1052_p3;
reg   [15:0] Cluster_1_Deposits2_1_reg_1343;
wire   [1:0] Cluster_1_Eta18_1_Cl_fu_1060_p3;
reg   [1:0] Cluster_1_Eta18_1_Cl_reg_1348;
wire   [1:0] Cluster_1_Eta17_1_Cl_fu_1068_p3;
reg   [1:0] Cluster_1_Eta17_1_Cl_reg_1353;
wire   [1:0] Cluster_1_Phi33_1_Cl_fu_1076_p3;
reg   [1:0] Cluster_1_Phi33_1_Cl_reg_1358;
wire   [1:0] Cluster_1_Phi32_1_Cl_fu_1084_p3;
reg   [1:0] Cluster_1_Phi32_1_Cl_reg_1363;
wire   [15:0] Cluster_1_Deposits5_1_fu_1098_p3;
reg   [15:0] Cluster_1_Deposits5_1_reg_1368;
wire   [15:0] Cluster_1_Deposits4_1_fu_1106_p3;
reg   [15:0] Cluster_1_Deposits4_1_reg_1373;
wire   [1:0] Cluster_1_Eta2025_1_s_fu_1114_p3;
reg   [1:0] Cluster_1_Eta2025_1_s_reg_1378;
wire   [1:0] Cluster_1_Eta19_1_Cl_fu_1122_p3;
reg   [1:0] Cluster_1_Eta19_1_Cl_reg_1383;
wire   [1:0] Cluster_1_Phi35_1_Cl_fu_1130_p3;
reg   [1:0] Cluster_1_Phi35_1_Cl_reg_1388;
wire   [1:0] Cluster_1_Phi34_1_Cl_fu_1138_p3;
reg   [1:0] Cluster_1_Phi34_1_Cl_reg_1393;
wire   [15:0] Cluster_1_Deposits7_1_fu_1152_p3;
reg   [15:0] Cluster_1_Deposits7_1_reg_1398;
wire   [15:0] Cluster_1_Deposits6_1_fu_1160_p3;
reg   [15:0] Cluster_1_Deposits6_1_reg_1403;
wire   [1:0] Cluster_1_Eta22_1_Cl_fu_1168_p3;
reg   [1:0] Cluster_1_Eta22_1_Cl_reg_1408;
wire   [1:0] Cluster_1_Eta21_1_Cl_fu_1176_p3;
reg   [1:0] Cluster_1_Eta21_1_Cl_reg_1413;
wire   [1:0] Cluster_1_Phi3744_1_s_fu_1184_p3;
reg   [1:0] Cluster_1_Phi3744_1_s_reg_1418;
wire   [1:0] Cluster_1_Phi36_1_Cl_fu_1192_p3;
reg   [1:0] Cluster_1_Phi36_1_Cl_reg_1423;
wire   [15:0] Cluster_1_Deposits13_1_fu_1206_p3;
reg   [15:0] Cluster_1_Deposits13_1_reg_1428;
wire   [15:0] Cluster_1_Deposits12_3_fu_1214_p3;
reg   [15:0] Cluster_1_Deposits12_3_reg_1433;
wire   [1:0] Cluster_1_Eta28_1_Cl_fu_1222_p3;
reg   [1:0] Cluster_1_Eta28_1_Cl_reg_1438;
wire   [1:0] Cluster_1_Eta27_1_Cl_fu_1230_p3;
reg   [1:0] Cluster_1_Eta27_1_Cl_reg_1443;
wire   [1:0] Cluster_1_Phi43_1_Cl_fu_1238_p3;
reg   [1:0] Cluster_1_Phi43_1_Cl_reg_1448;
wire   [1:0] Cluster_1_Phi42_1_Cl_fu_1246_p3;
reg   [1:0] Cluster_1_Phi42_1_Cl_reg_1453;
wire   [15:0] Cluster_1_Deposits15_1_fu_1260_p3;
reg   [15:0] Cluster_1_Deposits15_1_reg_1458;
wire   [15:0] Cluster_1_Deposits14_1_fu_1268_p3;
reg   [15:0] Cluster_1_Deposits14_1_reg_1463;
wire   [1:0] Cluster_1_Eta30_1_Cl_fu_1276_p3;
reg   [1:0] Cluster_1_Eta30_1_Cl_reg_1468;
wire   [1:0] Cluster_1_Eta29_1_Cl_fu_1284_p3;
reg   [1:0] Cluster_1_Eta29_1_Cl_reg_1473;
wire   [1:0] Cluster_1_Phi45_1_Cl_fu_1292_p3;
reg   [1:0] Cluster_1_Phi45_1_Cl_reg_1478;
wire   [1:0] Cluster_1_Phi44_1_Cl_fu_1300_p3;
reg   [1:0] Cluster_1_Phi44_1_Cl_reg_1483;
wire   [15:0] call_ret_bitonic_1_16_fu_300_ap_return_0;
wire   [15:0] call_ret_bitonic_1_16_fu_300_ap_return_1;
wire   [15:0] call_ret_bitonic_1_16_fu_300_ap_return_2;
wire   [15:0] call_ret_bitonic_1_16_fu_300_ap_return_3;
wire   [15:0] call_ret_bitonic_1_16_fu_300_ap_return_4;
wire   [15:0] call_ret_bitonic_1_16_fu_300_ap_return_5;
wire   [15:0] call_ret_bitonic_1_16_fu_300_ap_return_6;
wire   [15:0] call_ret_bitonic_1_16_fu_300_ap_return_7;
wire   [15:0] call_ret_bitonic_1_16_fu_300_ap_return_8;
wire   [15:0] call_ret_bitonic_1_16_fu_300_ap_return_9;
wire   [0:0] ap_CS_fsm_state2;
wire   [0:0] tmp_s_fu_340_p2;
wire   [1:0] Cluster_1_Phi_0_rea_1_fu_378_p1;
wire   [0:0] tmp_19_1_fu_398_p2;
wire   [1:0] Cluster_1_Phi_1_rea_1_fu_436_p1;
wire   [0:0] tmp_19_2_fu_456_p2;
wire   [1:0] Cluster_1_Phi_2_rea_1_fu_494_p1;
wire   [0:0] tmp_19_3_fu_514_p2;
wire   [1:0] Cluster_1_Phi_3_rea_1_fu_552_p1;
wire   [0:0] tmp_2_fu_572_p2;
wire   [0:0] tmp_23_1_fu_594_p2;
wire   [0:0] tmp_23_2_fu_616_p2;
wire   [0:0] tmp_23_3_fu_638_p2;
wire   [15:0] p_read4_read_fu_346_p3;
wire   [15:0] p_read6_read2_fu_462_p3;
wire   [0:0] tmp_3_fu_660_p2;
wire   [1:0] p_read22_read_fu_478_p3;
wire   [1:0] p_read20_read_fu_362_p3;
wire   [1:0] p_read38_read_fu_498_p3;
wire   [1:0] p_read36_read_fu_382_p3;
wire   [15:0] p_read5_read1_fu_404_p3;
wire   [15:0] p_read7_read3_fu_520_p3;
wire   [0:0] tmp_4_fu_714_p2;
wire   [1:0] p_read23_read_fu_536_p3;
wire   [1:0] p_read21_read_fu_420_p3;
wire   [1:0] p_read39_read_fu_556_p3;
wire   [1:0] p_read37_read_fu_440_p3;
wire   [15:0] p_read_read4_fu_354_p3;
wire   [15:0] p_read2_read6_fu_470_p3;
wire   [0:0] tmp_28_1_fu_768_p2;
wire   [1:0] p_read18_read_fu_486_p3;
wire   [1:0] p_read16_read_fu_370_p3;
wire   [1:0] p_read34_read_fu_506_p3;
wire   [1:0] p_read32_read_fu_390_p3;
wire   [15:0] p_read1_read5_fu_412_p3;
wire   [15:0] p_read3_read7_fu_528_p3;
wire   [0:0] tmp_33_1_fu_822_p2;
wire   [1:0] p_read19_read_fu_544_p3;
wire   [1:0] p_read17_read_fu_428_p3;
wire   [1:0] p_read35_read_fu_564_p3;
wire   [1:0] p_read33_read_fu_448_p3;
wire   [0:0] tmp_38_1_fu_876_p2;
wire   [1:0] p_read4_fu_622_p3;
wire   [1:0] p_read_fu_578_p3;
wire   [1:0] p_read5_fu_630_p3;
wire   [1:0] p_read1_fu_586_p3;
wire   [0:0] tmp_43_1_fu_930_p2;
wire   [1:0] p_read6_fu_644_p3;
wire   [1:0] p_read2_fu_600_p3;
wire   [1:0] p_read7_fu_652_p3;
wire   [1:0] p_read3_fu_608_p3;
wire   [15:0] Cluster_1_Deposits2_s_fu_666_p3;
wire   [15:0] Cluster_1_Deposits3_s_fu_720_p3;
wire   [0:0] tmp_5_fu_984_p2;
wire   [1:0] Cluster_1_Eta18_0_Cl_fu_736_p3;
wire   [1:0] Cluster_1_Eta17_0_Cl_fu_682_p3;
wire   [1:0] Cluster_1_Phi33_0_Cl_fu_752_p3;
wire   [1:0] Cluster_1_Phi32_0_Cl_fu_698_p3;
wire   [15:0] Cluster_1_Deposits_fu_674_p3;
wire   [15:0] Cluster_1_Deposits1_fu_728_p3;
wire   [0:0] tmp_48_1_fu_1038_p2;
wire   [1:0] Cluster_1_Eta16_0_Cl_fu_744_p3;
wire   [1:0] Cluster_1_Eta_0_Clus_fu_690_p3;
wire   [1:0] Cluster_1_Phi31_0_Cl_fu_760_p3;
wire   [1:0] Cluster_1_Phi_0_Clus_fu_706_p3;
wire   [15:0] Cluster_1_Deposits6_s_fu_774_p3;
wire   [15:0] Cluster_1_Deposits7_s_fu_828_p3;
wire   [0:0] tmp_48_2_fu_1092_p2;
wire   [1:0] Cluster_1_Eta22_0_Cl_fu_844_p3;
wire   [1:0] Cluster_1_Eta21_0_Cl_fu_790_p3;
wire   [1:0] Cluster_1_Phi3744_0_s_fu_860_p3;
wire   [1:0] Cluster_1_Phi36_0_Cl_fu_806_p3;
wire   [15:0] Cluster_1_Deposits4_s_fu_782_p3;
wire   [15:0] Cluster_1_Deposits5_s_fu_836_p3;
wire   [0:0] tmp_48_3_fu_1146_p2;
wire   [1:0] Cluster_1_Eta2025_0_s_fu_852_p3;
wire   [1:0] Cluster_1_Eta19_0_Cl_fu_798_p3;
wire   [1:0] Cluster_1_Phi35_0_Cl_fu_868_p3;
wire   [1:0] Cluster_1_Phi34_0_Cl_fu_814_p3;
wire   [15:0] Cluster_1_Deposits2_fu_882_p3;
wire   [15:0] Cluster_1_Deposits3_fu_936_p3;
wire   [0:0] tmp_53_2_fu_1200_p2;
wire   [1:0] Cluster_1_Eta30_0_Cl_fu_952_p3;
wire   [1:0] Cluster_1_Eta29_0_Cl_fu_898_p3;
wire   [1:0] Cluster_1_Phi45_0_Cl_fu_968_p3;
wire   [1:0] Cluster_1_Phi44_0_Cl_fu_914_p3;
wire   [15:0] Cluster_1_Deposits12_1_fu_890_p3;
wire   [15:0] Cluster_1_Deposits4_fu_944_p3;
wire   [0:0] tmp_53_3_fu_1254_p2;
wire   [1:0] Cluster_1_Eta28_0_Cl_fu_960_p3;
wire   [1:0] Cluster_1_Eta27_0_Cl_fu_906_p3;
wire   [1:0] Cluster_1_Phi43_0_Cl_fu_976_p3;
wire   [1:0] Cluster_1_Phi42_0_Cl_fu_922_p3;
reg   [1:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'b1;
end

bitonic_1_16 call_ret_bitonic_1_16_fu_300(
    .Cluster_1_Deposits_0(Cluster_1_Deposits12_2_reg_1308),
    .Cluster_1_Deposits_1(Cluster_1_Deposits_1_8_reg_1313),
    .Cluster_1_Deposits_2(Cluster_1_Deposits3_1_reg_1338),
    .Cluster_1_Deposits_3(Cluster_1_Deposits2_1_reg_1343),
    .Cluster_1_Deposits_4(Cluster_1_Deposits5_1_reg_1368),
    .Cluster_1_Deposits_5(Cluster_1_Deposits4_1_reg_1373),
    .Cluster_1_Deposits_6(Cluster_1_Deposits7_1_reg_1398),
    .Cluster_1_Deposits_7(Cluster_1_Deposits6_1_reg_1403),
    .Cluster_1_Deposits_1_12(Cluster_1_Deposits13_1_reg_1428),
    .Cluster_1_Deposits_1_13(Cluster_1_Deposits12_3_reg_1433),
    .Cluster_1_Deposits_1_14(Cluster_1_Deposits15_1_reg_1458),
    .Cluster_1_Deposits_1_15(Cluster_1_Deposits14_1_reg_1463),
    .Cluster_1_Eta_0_rea(Cluster_1_Eta16_1_Cl_reg_1318),
    .Cluster_1_Eta_1_rea(Cluster_1_Eta_1_Clus_reg_1323),
    .Cluster_1_Eta_2_rea(Cluster_1_Eta18_1_Cl_reg_1348),
    .Cluster_1_Eta_3_rea(Cluster_1_Eta17_1_Cl_reg_1353),
    .Cluster_1_Eta_4_rea(Cluster_1_Eta2025_1_s_reg_1378),
    .Cluster_1_Eta_5_rea(Cluster_1_Eta19_1_Cl_reg_1383),
    .Cluster_1_Eta_6_rea(Cluster_1_Eta22_1_Cl_reg_1408),
    .Cluster_1_Eta_7_rea(Cluster_1_Eta21_1_Cl_reg_1413),
    .Cluster_1_Eta_12_re(Cluster_1_Eta28_1_Cl_reg_1438),
    .Cluster_1_Eta_13_re(Cluster_1_Eta27_1_Cl_reg_1443),
    .Cluster_1_Eta_14_re(Cluster_1_Eta30_1_Cl_reg_1468),
    .Cluster_1_Eta_15_re(Cluster_1_Eta29_1_Cl_reg_1473),
    .Cluster_1_Phi_0_rea(Cluster_1_Phi31_1_Cl_reg_1328),
    .Cluster_1_Phi_1_rea(Cluster_1_Phi_1_Clus_reg_1333),
    .Cluster_1_Phi_2_rea(Cluster_1_Phi33_1_Cl_reg_1358),
    .Cluster_1_Phi_3_rea(Cluster_1_Phi32_1_Cl_reg_1363),
    .Cluster_1_Phi_4_rea(Cluster_1_Phi35_1_Cl_reg_1388),
    .Cluster_1_Phi_5_rea(Cluster_1_Phi34_1_Cl_reg_1393),
    .Cluster_1_Phi_6_rea(Cluster_1_Phi3744_1_s_reg_1418),
    .Cluster_1_Phi_7_rea(Cluster_1_Phi36_1_Cl_reg_1423),
    .Cluster_1_Phi_12_re(Cluster_1_Phi43_1_Cl_reg_1448),
    .Cluster_1_Phi_13_re(Cluster_1_Phi42_1_Cl_reg_1453),
    .Cluster_1_Phi_14_re(Cluster_1_Phi45_1_Cl_reg_1478),
    .Cluster_1_Phi_15_re(Cluster_1_Phi44_1_Cl_reg_1483),
    .ap_return_0(call_ret_bitonic_1_16_fu_300_ap_return_0),
    .ap_return_1(call_ret_bitonic_1_16_fu_300_ap_return_1),
    .ap_return_2(call_ret_bitonic_1_16_fu_300_ap_return_2),
    .ap_return_3(call_ret_bitonic_1_16_fu_300_ap_return_3),
    .ap_return_4(call_ret_bitonic_1_16_fu_300_ap_return_4),
    .ap_return_5(call_ret_bitonic_1_16_fu_300_ap_return_5),
    .ap_return_6(call_ret_bitonic_1_16_fu_300_ap_return_6),
    .ap_return_7(call_ret_bitonic_1_16_fu_300_ap_return_7),
    .ap_return_8(call_ret_bitonic_1_16_fu_300_ap_return_8),
    .ap_return_9(call_ret_bitonic_1_16_fu_300_ap_return_9)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_CS_fsm_state1 == 1'b1) & (1'b1 == ap_ce) & ~(ap_start == 1'b0))) begin
        Cluster_1_Deposits12_2_reg_1308 <= Cluster_1_Deposits12_2_fu_990_p3;
        Cluster_1_Deposits12_3_reg_1433 <= Cluster_1_Deposits12_3_fu_1214_p3;
        Cluster_1_Deposits13_1_reg_1428 <= Cluster_1_Deposits13_1_fu_1206_p3;
        Cluster_1_Deposits14_1_reg_1463 <= Cluster_1_Deposits14_1_fu_1268_p3;
        Cluster_1_Deposits15_1_reg_1458 <= Cluster_1_Deposits15_1_fu_1260_p3;
        Cluster_1_Deposits2_1_reg_1343 <= Cluster_1_Deposits2_1_fu_1052_p3;
        Cluster_1_Deposits3_1_reg_1338 <= Cluster_1_Deposits3_1_fu_1044_p3;
        Cluster_1_Deposits4_1_reg_1373 <= Cluster_1_Deposits4_1_fu_1106_p3;
        Cluster_1_Deposits5_1_reg_1368 <= Cluster_1_Deposits5_1_fu_1098_p3;
        Cluster_1_Deposits6_1_reg_1403 <= Cluster_1_Deposits6_1_fu_1160_p3;
        Cluster_1_Deposits7_1_reg_1398 <= Cluster_1_Deposits7_1_fu_1152_p3;
        Cluster_1_Deposits_1_8_reg_1313 <= Cluster_1_Deposits_1_8_fu_998_p3;
        Cluster_1_Eta16_1_Cl_reg_1318 <= Cluster_1_Eta16_1_Cl_fu_1006_p3;
        Cluster_1_Eta17_1_Cl_reg_1353 <= Cluster_1_Eta17_1_Cl_fu_1068_p3;
        Cluster_1_Eta18_1_Cl_reg_1348 <= Cluster_1_Eta18_1_Cl_fu_1060_p3;
        Cluster_1_Eta19_1_Cl_reg_1383 <= Cluster_1_Eta19_1_Cl_fu_1122_p3;
        Cluster_1_Eta2025_1_s_reg_1378 <= Cluster_1_Eta2025_1_s_fu_1114_p3;
        Cluster_1_Eta21_1_Cl_reg_1413 <= Cluster_1_Eta21_1_Cl_fu_1176_p3;
        Cluster_1_Eta22_1_Cl_reg_1408 <= Cluster_1_Eta22_1_Cl_fu_1168_p3;
        Cluster_1_Eta27_1_Cl_reg_1443 <= Cluster_1_Eta27_1_Cl_fu_1230_p3;
        Cluster_1_Eta28_1_Cl_reg_1438 <= Cluster_1_Eta28_1_Cl_fu_1222_p3;
        Cluster_1_Eta29_1_Cl_reg_1473 <= Cluster_1_Eta29_1_Cl_fu_1284_p3;
        Cluster_1_Eta30_1_Cl_reg_1468 <= Cluster_1_Eta30_1_Cl_fu_1276_p3;
        Cluster_1_Eta_1_Clus_reg_1323 <= Cluster_1_Eta_1_Clus_fu_1014_p3;
        Cluster_1_Phi31_1_Cl_reg_1328 <= Cluster_1_Phi31_1_Cl_fu_1022_p3;
        Cluster_1_Phi32_1_Cl_reg_1363 <= Cluster_1_Phi32_1_Cl_fu_1084_p3;
        Cluster_1_Phi33_1_Cl_reg_1358 <= Cluster_1_Phi33_1_Cl_fu_1076_p3;
        Cluster_1_Phi34_1_Cl_reg_1393 <= Cluster_1_Phi34_1_Cl_fu_1138_p3;
        Cluster_1_Phi35_1_Cl_reg_1388 <= Cluster_1_Phi35_1_Cl_fu_1130_p3;
        Cluster_1_Phi36_1_Cl_reg_1423 <= Cluster_1_Phi36_1_Cl_fu_1192_p3;
        Cluster_1_Phi3744_1_s_reg_1418 <= Cluster_1_Phi3744_1_s_fu_1184_p3;
        Cluster_1_Phi42_1_Cl_reg_1453 <= Cluster_1_Phi42_1_Cl_fu_1246_p3;
        Cluster_1_Phi43_1_Cl_reg_1448 <= Cluster_1_Phi43_1_Cl_fu_1238_p3;
        Cluster_1_Phi44_1_Cl_reg_1483 <= Cluster_1_Phi44_1_Cl_fu_1300_p3;
        Cluster_1_Phi45_1_Cl_reg_1478 <= Cluster_1_Phi45_1_Cl_fu_1292_p3;
        Cluster_1_Phi_1_Clus_reg_1333 <= Cluster_1_Phi_1_Clus_fu_1030_p3;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_start) & (ap_CS_fsm_state1 == 1'b1)) | ((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_start) & (ap_CS_fsm_state1 == 1'b1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_ce) & ~(ap_start == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if ((1'b1 == ap_ce)) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign Cluster_1_Deposits12_1_fu_890_p3 = ((tmp_38_1_fu_876_p2[0:0] === 1'b1) ? Cluster_1_Deposits_8 : Cluster_1_Deposits_1_3);

assign Cluster_1_Deposits12_2_fu_990_p3 = ((tmp_5_fu_984_p2[0:0] === 1'b1) ? Cluster_1_Deposits3_s_fu_720_p3 : Cluster_1_Deposits2_s_fu_666_p3);

assign Cluster_1_Deposits12_3_fu_1214_p3 = ((tmp_53_2_fu_1200_p2[0:0] === 1'b1) ? Cluster_1_Deposits2_fu_882_p3 : Cluster_1_Deposits3_fu_936_p3);

assign Cluster_1_Deposits13_1_fu_1206_p3 = ((tmp_53_2_fu_1200_p2[0:0] === 1'b1) ? Cluster_1_Deposits3_fu_936_p3 : Cluster_1_Deposits2_fu_882_p3);

assign Cluster_1_Deposits14_1_fu_1268_p3 = ((tmp_53_3_fu_1254_p2[0:0] === 1'b1) ? Cluster_1_Deposits12_1_fu_890_p3 : Cluster_1_Deposits4_fu_944_p3);

assign Cluster_1_Deposits15_1_fu_1260_p3 = ((tmp_53_3_fu_1254_p2[0:0] === 1'b1) ? Cluster_1_Deposits4_fu_944_p3 : Cluster_1_Deposits12_1_fu_890_p3);

assign Cluster_1_Deposits1_fu_728_p3 = ((tmp_4_fu_714_p2[0:0] === 1'b1) ? p_read5_read1_fu_404_p3 : p_read7_read3_fu_520_p3);

assign Cluster_1_Deposits2_1_fu_1052_p3 = ((tmp_48_1_fu_1038_p2[0:0] === 1'b1) ? Cluster_1_Deposits_fu_674_p3 : Cluster_1_Deposits1_fu_728_p3);

assign Cluster_1_Deposits2_fu_882_p3 = ((tmp_38_1_fu_876_p2[0:0] === 1'b1) ? Cluster_1_Deposits_1_3 : Cluster_1_Deposits_8);

assign Cluster_1_Deposits2_s_fu_666_p3 = ((tmp_3_fu_660_p2[0:0] === 1'b1) ? p_read6_read2_fu_462_p3 : p_read4_read_fu_346_p3);

assign Cluster_1_Deposits3_1_fu_1044_p3 = ((tmp_48_1_fu_1038_p2[0:0] === 1'b1) ? Cluster_1_Deposits1_fu_728_p3 : Cluster_1_Deposits_fu_674_p3);

assign Cluster_1_Deposits3_fu_936_p3 = ((tmp_43_1_fu_930_p2[0:0] === 1'b1) ? Cluster_1_Deposits_1_4 : Cluster_1_Deposits_9);

assign Cluster_1_Deposits3_s_fu_720_p3 = ((tmp_4_fu_714_p2[0:0] === 1'b1) ? p_read7_read3_fu_520_p3 : p_read5_read1_fu_404_p3);

assign Cluster_1_Deposits4_1_fu_1106_p3 = ((tmp_48_2_fu_1092_p2[0:0] === 1'b1) ? Cluster_1_Deposits6_s_fu_774_p3 : Cluster_1_Deposits7_s_fu_828_p3);

assign Cluster_1_Deposits4_fu_944_p3 = ((tmp_43_1_fu_930_p2[0:0] === 1'b1) ? Cluster_1_Deposits_9 : Cluster_1_Deposits_1_4);

assign Cluster_1_Deposits4_s_fu_782_p3 = ((tmp_28_1_fu_768_p2[0:0] === 1'b1) ? p_read_read4_fu_354_p3 : p_read2_read6_fu_470_p3);

assign Cluster_1_Deposits5_1_fu_1098_p3 = ((tmp_48_2_fu_1092_p2[0:0] === 1'b1) ? Cluster_1_Deposits7_s_fu_828_p3 : Cluster_1_Deposits6_s_fu_774_p3);

assign Cluster_1_Deposits5_s_fu_836_p3 = ((tmp_33_1_fu_822_p2[0:0] === 1'b1) ? p_read1_read5_fu_412_p3 : p_read3_read7_fu_528_p3);

assign Cluster_1_Deposits6_1_fu_1160_p3 = ((tmp_48_3_fu_1146_p2[0:0] === 1'b1) ? Cluster_1_Deposits4_s_fu_782_p3 : Cluster_1_Deposits5_s_fu_836_p3);

assign Cluster_1_Deposits6_s_fu_774_p3 = ((tmp_28_1_fu_768_p2[0:0] === 1'b1) ? p_read2_read6_fu_470_p3 : p_read_read4_fu_354_p3);

assign Cluster_1_Deposits7_1_fu_1152_p3 = ((tmp_48_3_fu_1146_p2[0:0] === 1'b1) ? Cluster_1_Deposits5_s_fu_836_p3 : Cluster_1_Deposits4_s_fu_782_p3);

assign Cluster_1_Deposits7_s_fu_828_p3 = ((tmp_33_1_fu_822_p2[0:0] === 1'b1) ? p_read3_read7_fu_528_p3 : p_read1_read5_fu_412_p3);

assign Cluster_1_Deposits_1_8_fu_998_p3 = ((tmp_5_fu_984_p2[0:0] === 1'b1) ? Cluster_1_Deposits2_s_fu_666_p3 : Cluster_1_Deposits3_s_fu_720_p3);

assign Cluster_1_Deposits_fu_674_p3 = ((tmp_3_fu_660_p2[0:0] === 1'b1) ? p_read4_read_fu_346_p3 : p_read6_read2_fu_462_p3);

assign Cluster_1_Eta16_0_Cl_fu_744_p3 = ((tmp_4_fu_714_p2[0:0] === 1'b1) ? p_read21_read_fu_420_p3 : p_read23_read_fu_536_p3);

assign Cluster_1_Eta16_1_Cl_fu_1006_p3 = ((tmp_5_fu_984_p2[0:0] === 1'b1) ? Cluster_1_Eta18_0_Cl_fu_736_p3 : Cluster_1_Eta17_0_Cl_fu_682_p3);

assign Cluster_1_Eta17_0_Cl_fu_682_p3 = ((tmp_3_fu_660_p2[0:0] === 1'b1) ? p_read22_read_fu_478_p3 : p_read20_read_fu_362_p3);

assign Cluster_1_Eta17_1_Cl_fu_1068_p3 = ((tmp_48_1_fu_1038_p2[0:0] === 1'b1) ? Cluster_1_Eta_0_Clus_fu_690_p3 : Cluster_1_Eta16_0_Cl_fu_744_p3);

assign Cluster_1_Eta18_0_Cl_fu_736_p3 = ((tmp_4_fu_714_p2[0:0] === 1'b1) ? p_read23_read_fu_536_p3 : p_read21_read_fu_420_p3);

assign Cluster_1_Eta18_1_Cl_fu_1060_p3 = ((tmp_48_1_fu_1038_p2[0:0] === 1'b1) ? Cluster_1_Eta16_0_Cl_fu_744_p3 : Cluster_1_Eta_0_Clus_fu_690_p3);

assign Cluster_1_Eta19_0_Cl_fu_798_p3 = ((tmp_28_1_fu_768_p2[0:0] === 1'b1) ? p_read16_read_fu_370_p3 : p_read18_read_fu_486_p3);

assign Cluster_1_Eta19_1_Cl_fu_1122_p3 = ((tmp_48_2_fu_1092_p2[0:0] === 1'b1) ? Cluster_1_Eta21_0_Cl_fu_790_p3 : Cluster_1_Eta22_0_Cl_fu_844_p3);

assign Cluster_1_Eta2025_0_s_fu_852_p3 = ((tmp_33_1_fu_822_p2[0:0] === 1'b1) ? p_read17_read_fu_428_p3 : p_read19_read_fu_544_p3);

assign Cluster_1_Eta2025_1_s_fu_1114_p3 = ((tmp_48_2_fu_1092_p2[0:0] === 1'b1) ? Cluster_1_Eta22_0_Cl_fu_844_p3 : Cluster_1_Eta21_0_Cl_fu_790_p3);

assign Cluster_1_Eta21_0_Cl_fu_790_p3 = ((tmp_28_1_fu_768_p2[0:0] === 1'b1) ? p_read18_read_fu_486_p3 : p_read16_read_fu_370_p3);

assign Cluster_1_Eta21_1_Cl_fu_1176_p3 = ((tmp_48_3_fu_1146_p2[0:0] === 1'b1) ? Cluster_1_Eta19_0_Cl_fu_798_p3 : Cluster_1_Eta2025_0_s_fu_852_p3);

assign Cluster_1_Eta22_0_Cl_fu_844_p3 = ((tmp_33_1_fu_822_p2[0:0] === 1'b1) ? p_read19_read_fu_544_p3 : p_read17_read_fu_428_p3);

assign Cluster_1_Eta22_1_Cl_fu_1168_p3 = ((tmp_48_3_fu_1146_p2[0:0] === 1'b1) ? Cluster_1_Eta2025_0_s_fu_852_p3 : Cluster_1_Eta19_0_Cl_fu_798_p3);

assign Cluster_1_Eta27_0_Cl_fu_906_p3 = ((tmp_38_1_fu_876_p2[0:0] === 1'b1) ? p_read_fu_578_p3 : p_read4_fu_622_p3);

assign Cluster_1_Eta27_1_Cl_fu_1230_p3 = ((tmp_53_2_fu_1200_p2[0:0] === 1'b1) ? Cluster_1_Eta29_0_Cl_fu_898_p3 : Cluster_1_Eta30_0_Cl_fu_952_p3);

assign Cluster_1_Eta28_0_Cl_fu_960_p3 = ((tmp_43_1_fu_930_p2[0:0] === 1'b1) ? p_read2_fu_600_p3 : p_read6_fu_644_p3);

assign Cluster_1_Eta28_1_Cl_fu_1222_p3 = ((tmp_53_2_fu_1200_p2[0:0] === 1'b1) ? Cluster_1_Eta30_0_Cl_fu_952_p3 : Cluster_1_Eta29_0_Cl_fu_898_p3);

assign Cluster_1_Eta29_0_Cl_fu_898_p3 = ((tmp_38_1_fu_876_p2[0:0] === 1'b1) ? p_read4_fu_622_p3 : p_read_fu_578_p3);

assign Cluster_1_Eta29_1_Cl_fu_1284_p3 = ((tmp_53_3_fu_1254_p2[0:0] === 1'b1) ? Cluster_1_Eta27_0_Cl_fu_906_p3 : Cluster_1_Eta28_0_Cl_fu_960_p3);

assign Cluster_1_Eta30_0_Cl_fu_952_p3 = ((tmp_43_1_fu_930_p2[0:0] === 1'b1) ? p_read6_fu_644_p3 : p_read2_fu_600_p3);

assign Cluster_1_Eta30_1_Cl_fu_1276_p3 = ((tmp_53_3_fu_1254_p2[0:0] === 1'b1) ? Cluster_1_Eta28_0_Cl_fu_960_p3 : Cluster_1_Eta27_0_Cl_fu_906_p3);

assign Cluster_1_Eta_0_Clus_fu_690_p3 = ((tmp_3_fu_660_p2[0:0] === 1'b1) ? p_read20_read_fu_362_p3 : p_read22_read_fu_478_p3);

assign Cluster_1_Eta_1_Clus_fu_1014_p3 = ((tmp_5_fu_984_p2[0:0] === 1'b1) ? Cluster_1_Eta17_0_Cl_fu_682_p3 : Cluster_1_Eta18_0_Cl_fu_736_p3);

assign Cluster_1_Phi31_0_Cl_fu_760_p3 = ((tmp_4_fu_714_p2[0:0] === 1'b1) ? p_read37_read_fu_440_p3 : p_read39_read_fu_556_p3);

assign Cluster_1_Phi31_1_Cl_fu_1022_p3 = ((tmp_5_fu_984_p2[0:0] === 1'b1) ? Cluster_1_Phi33_0_Cl_fu_752_p3 : Cluster_1_Phi32_0_Cl_fu_698_p3);

assign Cluster_1_Phi32_0_Cl_fu_698_p3 = ((tmp_3_fu_660_p2[0:0] === 1'b1) ? p_read38_read_fu_498_p3 : p_read36_read_fu_382_p3);

assign Cluster_1_Phi32_1_Cl_fu_1084_p3 = ((tmp_48_1_fu_1038_p2[0:0] === 1'b1) ? Cluster_1_Phi_0_Clus_fu_706_p3 : Cluster_1_Phi31_0_Cl_fu_760_p3);

assign Cluster_1_Phi33_0_Cl_fu_752_p3 = ((tmp_4_fu_714_p2[0:0] === 1'b1) ? p_read39_read_fu_556_p3 : p_read37_read_fu_440_p3);

assign Cluster_1_Phi33_1_Cl_fu_1076_p3 = ((tmp_48_1_fu_1038_p2[0:0] === 1'b1) ? Cluster_1_Phi31_0_Cl_fu_760_p3 : Cluster_1_Phi_0_Clus_fu_706_p3);

assign Cluster_1_Phi34_0_Cl_fu_814_p3 = ((tmp_28_1_fu_768_p2[0:0] === 1'b1) ? p_read32_read_fu_390_p3 : p_read34_read_fu_506_p3);

assign Cluster_1_Phi34_1_Cl_fu_1138_p3 = ((tmp_48_2_fu_1092_p2[0:0] === 1'b1) ? Cluster_1_Phi36_0_Cl_fu_806_p3 : Cluster_1_Phi3744_0_s_fu_860_p3);

assign Cluster_1_Phi35_0_Cl_fu_868_p3 = ((tmp_33_1_fu_822_p2[0:0] === 1'b1) ? p_read33_read_fu_448_p3 : p_read35_read_fu_564_p3);

assign Cluster_1_Phi35_1_Cl_fu_1130_p3 = ((tmp_48_2_fu_1092_p2[0:0] === 1'b1) ? Cluster_1_Phi3744_0_s_fu_860_p3 : Cluster_1_Phi36_0_Cl_fu_806_p3);

assign Cluster_1_Phi36_0_Cl_fu_806_p3 = ((tmp_28_1_fu_768_p2[0:0] === 1'b1) ? p_read34_read_fu_506_p3 : p_read32_read_fu_390_p3);

assign Cluster_1_Phi36_1_Cl_fu_1192_p3 = ((tmp_48_3_fu_1146_p2[0:0] === 1'b1) ? Cluster_1_Phi34_0_Cl_fu_814_p3 : Cluster_1_Phi35_0_Cl_fu_868_p3);

assign Cluster_1_Phi3744_0_s_fu_860_p3 = ((tmp_33_1_fu_822_p2[0:0] === 1'b1) ? p_read35_read_fu_564_p3 : p_read33_read_fu_448_p3);

assign Cluster_1_Phi3744_1_s_fu_1184_p3 = ((tmp_48_3_fu_1146_p2[0:0] === 1'b1) ? Cluster_1_Phi35_0_Cl_fu_868_p3 : Cluster_1_Phi34_0_Cl_fu_814_p3);

assign Cluster_1_Phi42_0_Cl_fu_922_p3 = ((tmp_38_1_fu_876_p2[0:0] === 1'b1) ? p_read1_fu_586_p3 : p_read5_fu_630_p3);

assign Cluster_1_Phi42_1_Cl_fu_1246_p3 = ((tmp_53_2_fu_1200_p2[0:0] === 1'b1) ? Cluster_1_Phi44_0_Cl_fu_914_p3 : Cluster_1_Phi45_0_Cl_fu_968_p3);

assign Cluster_1_Phi43_0_Cl_fu_976_p3 = ((tmp_43_1_fu_930_p2[0:0] === 1'b1) ? p_read3_fu_608_p3 : p_read7_fu_652_p3);

assign Cluster_1_Phi43_1_Cl_fu_1238_p3 = ((tmp_53_2_fu_1200_p2[0:0] === 1'b1) ? Cluster_1_Phi45_0_Cl_fu_968_p3 : Cluster_1_Phi44_0_Cl_fu_914_p3);

assign Cluster_1_Phi44_0_Cl_fu_914_p3 = ((tmp_38_1_fu_876_p2[0:0] === 1'b1) ? p_read5_fu_630_p3 : p_read1_fu_586_p3);

assign Cluster_1_Phi44_1_Cl_fu_1300_p3 = ((tmp_53_3_fu_1254_p2[0:0] === 1'b1) ? Cluster_1_Phi42_0_Cl_fu_922_p3 : Cluster_1_Phi43_0_Cl_fu_976_p3);

assign Cluster_1_Phi45_0_Cl_fu_968_p3 = ((tmp_43_1_fu_930_p2[0:0] === 1'b1) ? p_read7_fu_652_p3 : p_read3_fu_608_p3);

assign Cluster_1_Phi45_1_Cl_fu_1292_p3 = ((tmp_53_3_fu_1254_p2[0:0] === 1'b1) ? Cluster_1_Phi43_0_Cl_fu_976_p3 : Cluster_1_Phi42_0_Cl_fu_922_p3);

assign Cluster_1_Phi_0_Clus_fu_706_p3 = ((tmp_3_fu_660_p2[0:0] === 1'b1) ? p_read36_read_fu_382_p3 : p_read38_read_fu_498_p3);

assign Cluster_1_Phi_0_rea_1_fu_378_p1 = Cluster_1_Phi_0_rea;

assign Cluster_1_Phi_1_Clus_fu_1030_p3 = ((tmp_5_fu_984_p2[0:0] === 1'b1) ? Cluster_1_Phi32_0_Cl_fu_698_p3 : Cluster_1_Phi33_0_Cl_fu_752_p3);

assign Cluster_1_Phi_1_rea_1_fu_436_p1 = Cluster_1_Phi_1_rea;

assign Cluster_1_Phi_2_rea_1_fu_494_p1 = Cluster_1_Phi_2_rea;

assign Cluster_1_Phi_3_rea_1_fu_552_p1 = Cluster_1_Phi_3_rea;

assign ap_CS_fsm_state1 = ap_CS_fsm[ap_const_lv32_0];

assign ap_CS_fsm_state2 = ap_CS_fsm[ap_const_lv32_1];

assign ap_return_0 = call_ret_bitonic_1_16_fu_300_ap_return_0;

assign ap_return_1 = call_ret_bitonic_1_16_fu_300_ap_return_1;

assign ap_return_2 = call_ret_bitonic_1_16_fu_300_ap_return_2;

assign ap_return_3 = call_ret_bitonic_1_16_fu_300_ap_return_3;

assign ap_return_4 = call_ret_bitonic_1_16_fu_300_ap_return_4;

assign ap_return_5 = call_ret_bitonic_1_16_fu_300_ap_return_5;

assign ap_return_6 = call_ret_bitonic_1_16_fu_300_ap_return_6;

assign ap_return_7 = call_ret_bitonic_1_16_fu_300_ap_return_7;

assign ap_return_8 = call_ret_bitonic_1_16_fu_300_ap_return_8;

assign ap_return_9 = call_ret_bitonic_1_16_fu_300_ap_return_9;

assign p_read16_read_fu_370_p3 = ((tmp_s_fu_340_p2[0:0] === 1'b1) ? Cluster_1_Eta_0_rea : Cluster_1_Eta_4_rea);

assign p_read17_read_fu_428_p3 = ((tmp_19_1_fu_398_p2[0:0] === 1'b1) ? Cluster_1_Eta_1_rea : Cluster_1_Eta_5_rea);

assign p_read18_read_fu_486_p3 = ((tmp_19_2_fu_456_p2[0:0] === 1'b1) ? Cluster_1_Eta_2_rea : Cluster_1_Eta_6_rea);

assign p_read19_read_fu_544_p3 = ((tmp_19_3_fu_514_p2[0:0] === 1'b1) ? Cluster_1_Eta_3_rea : Cluster_1_Eta_7_rea);

assign p_read1_fu_586_p3 = ((tmp_2_fu_572_p2[0:0] === 1'b1) ? ap_const_lv2_0 : Cluster_1_Phi_8_rea);

assign p_read1_read5_fu_412_p3 = ((tmp_19_1_fu_398_p2[0:0] === 1'b1) ? Cluster_1_Deposits_1 : Cluster_1_Deposits_5);

assign p_read20_read_fu_362_p3 = ((tmp_s_fu_340_p2[0:0] === 1'b1) ? Cluster_1_Eta_4_rea : Cluster_1_Eta_0_rea);

assign p_read21_read_fu_420_p3 = ((tmp_19_1_fu_398_p2[0:0] === 1'b1) ? Cluster_1_Eta_5_rea : Cluster_1_Eta_1_rea);

assign p_read22_read_fu_478_p3 = ((tmp_19_2_fu_456_p2[0:0] === 1'b1) ? Cluster_1_Eta_6_rea : Cluster_1_Eta_2_rea);

assign p_read23_read_fu_536_p3 = ((tmp_19_3_fu_514_p2[0:0] === 1'b1) ? Cluster_1_Eta_7_rea : Cluster_1_Eta_3_rea);

assign p_read2_fu_600_p3 = ((tmp_23_1_fu_594_p2[0:0] === 1'b1) ? ap_const_lv2_0 : Cluster_1_Eta_9_rea);

assign p_read2_read6_fu_470_p3 = ((tmp_19_2_fu_456_p2[0:0] === 1'b1) ? Cluster_1_Deposits_2 : Cluster_1_Deposits_6);

assign p_read32_read_fu_390_p3 = ((tmp_s_fu_340_p2[0:0] === 1'b1) ? Cluster_1_Phi_0_rea_1_fu_378_p1 : Cluster_1_Phi_4_rea);

assign p_read33_read_fu_448_p3 = ((tmp_19_1_fu_398_p2[0:0] === 1'b1) ? Cluster_1_Phi_1_rea_1_fu_436_p1 : Cluster_1_Phi_5_rea);

assign p_read34_read_fu_506_p3 = ((tmp_19_2_fu_456_p2[0:0] === 1'b1) ? Cluster_1_Phi_2_rea_1_fu_494_p1 : Cluster_1_Phi_6_rea);

assign p_read35_read_fu_564_p3 = ((tmp_19_3_fu_514_p2[0:0] === 1'b1) ? Cluster_1_Phi_3_rea_1_fu_552_p1 : Cluster_1_Phi_7_rea);

assign p_read36_read_fu_382_p3 = ((tmp_s_fu_340_p2[0:0] === 1'b1) ? Cluster_1_Phi_4_rea : Cluster_1_Phi_0_rea_1_fu_378_p1);

assign p_read37_read_fu_440_p3 = ((tmp_19_1_fu_398_p2[0:0] === 1'b1) ? Cluster_1_Phi_5_rea : Cluster_1_Phi_1_rea_1_fu_436_p1);

assign p_read38_read_fu_498_p3 = ((tmp_19_2_fu_456_p2[0:0] === 1'b1) ? Cluster_1_Phi_6_rea : Cluster_1_Phi_2_rea_1_fu_494_p1);

assign p_read39_read_fu_556_p3 = ((tmp_19_3_fu_514_p2[0:0] === 1'b1) ? Cluster_1_Phi_7_rea : Cluster_1_Phi_3_rea_1_fu_552_p1);

assign p_read3_fu_608_p3 = ((tmp_23_1_fu_594_p2[0:0] === 1'b1) ? ap_const_lv2_0 : Cluster_1_Phi_9_rea);

assign p_read3_read7_fu_528_p3 = ((tmp_19_3_fu_514_p2[0:0] === 1'b1) ? Cluster_1_Deposits_3 : Cluster_1_Deposits_7);

assign p_read4_fu_622_p3 = ((tmp_23_2_fu_616_p2[0:0] === 1'b1) ? ap_const_lv2_0 : Cluster_1_Eta_10_re);

assign p_read4_read_fu_346_p3 = ((tmp_s_fu_340_p2[0:0] === 1'b1) ? Cluster_1_Deposits_4 : Cluster_1_Deposits_0);

assign p_read5_fu_630_p3 = ((tmp_23_2_fu_616_p2[0:0] === 1'b1) ? ap_const_lv2_0 : Cluster_1_Phi_10_re);

assign p_read5_read1_fu_404_p3 = ((tmp_19_1_fu_398_p2[0:0] === 1'b1) ? Cluster_1_Deposits_5 : Cluster_1_Deposits_1);

assign p_read6_fu_644_p3 = ((tmp_23_3_fu_638_p2[0:0] === 1'b1) ? ap_const_lv2_0 : Cluster_1_Eta_11_re);

assign p_read6_read2_fu_462_p3 = ((tmp_19_2_fu_456_p2[0:0] === 1'b1) ? Cluster_1_Deposits_6 : Cluster_1_Deposits_2);

assign p_read7_fu_652_p3 = ((tmp_23_3_fu_638_p2[0:0] === 1'b1) ? ap_const_lv2_0 : Cluster_1_Phi_11_re);

assign p_read7_read3_fu_520_p3 = ((tmp_19_3_fu_514_p2[0:0] === 1'b1) ? Cluster_1_Deposits_7 : Cluster_1_Deposits_3);

assign p_read_fu_578_p3 = ((tmp_2_fu_572_p2[0:0] === 1'b1) ? ap_const_lv2_0 : Cluster_1_Eta_8_rea);

assign p_read_read4_fu_354_p3 = ((tmp_s_fu_340_p2[0:0] === 1'b1) ? Cluster_1_Deposits_0 : Cluster_1_Deposits_4);

assign tmp_19_1_fu_398_p2 = ((Cluster_1_Deposits_1 < Cluster_1_Deposits_5) ? 1'b1 : 1'b0);

assign tmp_19_2_fu_456_p2 = ((Cluster_1_Deposits_2 < Cluster_1_Deposits_6) ? 1'b1 : 1'b0);

assign tmp_19_3_fu_514_p2 = ((Cluster_1_Deposits_3 < Cluster_1_Deposits_7) ? 1'b1 : 1'b0);

assign tmp_23_1_fu_594_p2 = ((Cluster_1_Deposits_9 == ap_const_lv16_0) ? 1'b1 : 1'b0);

assign tmp_23_2_fu_616_p2 = ((Cluster_1_Deposits_1_3 == ap_const_lv16_0) ? 1'b1 : 1'b0);

assign tmp_23_3_fu_638_p2 = ((Cluster_1_Deposits_1_4 == ap_const_lv16_0) ? 1'b1 : 1'b0);

assign tmp_28_1_fu_768_p2 = ((p_read_read4_fu_354_p3 < p_read2_read6_fu_470_p3) ? 1'b1 : 1'b0);

assign tmp_2_fu_572_p2 = ((Cluster_1_Deposits_8 == ap_const_lv16_0) ? 1'b1 : 1'b0);

assign tmp_33_1_fu_822_p2 = ((p_read1_read5_fu_412_p3 < p_read3_read7_fu_528_p3) ? 1'b1 : 1'b0);

assign tmp_38_1_fu_876_p2 = ((Cluster_1_Deposits_8 > Cluster_1_Deposits_1_3) ? 1'b1 : 1'b0);

assign tmp_3_fu_660_p2 = ((p_read4_read_fu_346_p3 < p_read6_read2_fu_462_p3) ? 1'b1 : 1'b0);

assign tmp_43_1_fu_930_p2 = ((Cluster_1_Deposits_9 > Cluster_1_Deposits_1_4) ? 1'b1 : 1'b0);

assign tmp_48_1_fu_1038_p2 = ((Cluster_1_Deposits_fu_674_p3 < Cluster_1_Deposits1_fu_728_p3) ? 1'b1 : 1'b0);

assign tmp_48_2_fu_1092_p2 = ((Cluster_1_Deposits6_s_fu_774_p3 < Cluster_1_Deposits7_s_fu_828_p3) ? 1'b1 : 1'b0);

assign tmp_48_3_fu_1146_p2 = ((Cluster_1_Deposits4_s_fu_782_p3 < Cluster_1_Deposits5_s_fu_836_p3) ? 1'b1 : 1'b0);

assign tmp_4_fu_714_p2 = ((p_read5_read1_fu_404_p3 < p_read7_read3_fu_520_p3) ? 1'b1 : 1'b0);

assign tmp_53_2_fu_1200_p2 = ((Cluster_1_Deposits2_fu_882_p3 > Cluster_1_Deposits3_fu_936_p3) ? 1'b1 : 1'b0);

assign tmp_53_3_fu_1254_p2 = ((Cluster_1_Deposits12_1_fu_890_p3 > Cluster_1_Deposits4_fu_944_p3) ? 1'b1 : 1'b0);

assign tmp_5_fu_984_p2 = ((Cluster_1_Deposits2_s_fu_666_p3 < Cluster_1_Deposits3_s_fu_720_p3) ? 1'b1 : 1'b0);

assign tmp_s_fu_340_p2 = ((Cluster_1_Deposits_0 < Cluster_1_Deposits_4) ? 1'b1 : 1'b0);

endmodule //bitonic_1_8
