// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _bitonic_1_16_HH_
#define _bitonic_1_16_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct bitonic_1_16 : public sc_module {
    // Port declarations 46
    sc_in< sc_lv<16> > Cluster_1_Deposits_0;
    sc_in< sc_lv<16> > Cluster_1_Deposits_1;
    sc_in< sc_lv<16> > Cluster_1_Deposits_2;
    sc_in< sc_lv<16> > Cluster_1_Deposits_3;
    sc_in< sc_lv<16> > Cluster_1_Deposits_4;
    sc_in< sc_lv<16> > Cluster_1_Deposits_5;
    sc_in< sc_lv<16> > Cluster_1_Deposits_6;
    sc_in< sc_lv<16> > Cluster_1_Deposits_7;
    sc_in< sc_lv<16> > Cluster_1_Deposits_1_12;
    sc_in< sc_lv<16> > Cluster_1_Deposits_1_13;
    sc_in< sc_lv<16> > Cluster_1_Deposits_1_14;
    sc_in< sc_lv<16> > Cluster_1_Deposits_1_15;
    sc_in< sc_lv<2> > Cluster_1_Eta_0_rea;
    sc_in< sc_lv<2> > Cluster_1_Eta_1_rea;
    sc_in< sc_lv<2> > Cluster_1_Eta_2_rea;
    sc_in< sc_lv<2> > Cluster_1_Eta_3_rea;
    sc_in< sc_lv<2> > Cluster_1_Eta_4_rea;
    sc_in< sc_lv<2> > Cluster_1_Eta_5_rea;
    sc_in< sc_lv<2> > Cluster_1_Eta_6_rea;
    sc_in< sc_lv<2> > Cluster_1_Eta_7_rea;
    sc_in< sc_lv<2> > Cluster_1_Eta_12_re;
    sc_in< sc_lv<2> > Cluster_1_Eta_13_re;
    sc_in< sc_lv<2> > Cluster_1_Eta_14_re;
    sc_in< sc_lv<2> > Cluster_1_Eta_15_re;
    sc_in< sc_lv<2> > Cluster_1_Phi_0_rea;
    sc_in< sc_lv<2> > Cluster_1_Phi_1_rea;
    sc_in< sc_lv<2> > Cluster_1_Phi_2_rea;
    sc_in< sc_lv<2> > Cluster_1_Phi_3_rea;
    sc_in< sc_lv<2> > Cluster_1_Phi_4_rea;
    sc_in< sc_lv<2> > Cluster_1_Phi_5_rea;
    sc_in< sc_lv<2> > Cluster_1_Phi_6_rea;
    sc_in< sc_lv<2> > Cluster_1_Phi_7_rea;
    sc_in< sc_lv<2> > Cluster_1_Phi_12_re;
    sc_in< sc_lv<2> > Cluster_1_Phi_13_re;
    sc_in< sc_lv<2> > Cluster_1_Phi_14_re;
    sc_in< sc_lv<2> > Cluster_1_Phi_15_re;
    sc_out< sc_lv<16> > ap_return_0;
    sc_out< sc_lv<16> > ap_return_1;
    sc_out< sc_lv<16> > ap_return_2;
    sc_out< sc_lv<16> > ap_return_3;
    sc_out< sc_lv<16> > ap_return_4;
    sc_out< sc_lv<16> > ap_return_5;
    sc_out< sc_lv<16> > ap_return_6;
    sc_out< sc_lv<16> > ap_return_7;
    sc_out< sc_lv<16> > ap_return_8;
    sc_out< sc_lv<16> > ap_return_9;


    // Module declarations
    bitonic_1_16(sc_module_name name);
    SC_HAS_PROCESS(bitonic_1_16);

    ~bitonic_1_16();

    sc_trace_file* mVcdFile;

    sc_signal< sc_lv<1> > tmp_89_4_fu_294_p2;
    sc_signal< sc_lv<1> > tmp_89_5_fu_324_p2;
    sc_signal< sc_lv<1> > tmp_89_6_fu_354_p2;
    sc_signal< sc_lv<1> > tmp_89_7_fu_384_p2;
    sc_signal< sc_lv<16> > p_read12_read4_fu_300_p3;
    sc_signal< sc_lv<1> > tmp_6_fu_414_p2;
    sc_signal< sc_lv<2> > p_read28_read_fu_308_p3;
    sc_signal< sc_lv<2> > p_read44_read_fu_316_p3;
    sc_signal< sc_lv<16> > p_read13_read5_fu_330_p3;
    sc_signal< sc_lv<1> > tmp_93_1_fu_468_p2;
    sc_signal< sc_lv<2> > p_read29_read_fu_338_p3;
    sc_signal< sc_lv<2> > p_read45_read_fu_346_p3;
    sc_signal< sc_lv<16> > p_read14_read6_fu_360_p3;
    sc_signal< sc_lv<1> > tmp_93_2_fu_522_p2;
    sc_signal< sc_lv<2> > p_read30_read_fu_368_p3;
    sc_signal< sc_lv<2> > p_read46_read_fu_376_p3;
    sc_signal< sc_lv<16> > p_read15_read7_fu_390_p3;
    sc_signal< sc_lv<1> > tmp_93_3_fu_576_p2;
    sc_signal< sc_lv<2> > p_read31_read_fu_398_p3;
    sc_signal< sc_lv<2> > p_read47_read_fu_406_p3;
    sc_signal< sc_lv<16> > Cluster_1_Deposits4_s_fu_420_p3;
    sc_signal< sc_lv<16> > Cluster_1_Deposits6_s_fu_528_p3;
    sc_signal< sc_lv<1> > tmp_7_fu_630_p2;
    sc_signal< sc_lv<2> > Cluster_1_Eta21_0_Cl_fu_544_p3;
    sc_signal< sc_lv<2> > Cluster_1_Eta19_0_Cl_fu_436_p3;
    sc_signal< sc_lv<2> > Cluster_1_Phi36_0_Cl_fu_560_p3;
    sc_signal< sc_lv<2> > Cluster_1_Phi34_0_Cl_fu_452_p3;
    sc_signal< sc_lv<16> > Cluster_1_Deposits5_s_fu_474_p3;
    sc_signal< sc_lv<16> > Cluster_1_Deposits7_s_fu_582_p3;
    sc_signal< sc_lv<1> > tmp_8_fu_684_p2;
    sc_signal< sc_lv<2> > Cluster_1_Eta22_0_Cl_fu_598_p3;
    sc_signal< sc_lv<2> > Cluster_1_Eta2025_0_s_fu_490_p3;
    sc_signal< sc_lv<2> > Cluster_1_Phi3744_0_s_fu_614_p3;
    sc_signal< sc_lv<2> > Cluster_1_Phi35_0_Cl_fu_506_p3;
    sc_signal< sc_lv<16> > Cluster_1_Deposits_fu_428_p3;
    sc_signal< sc_lv<16> > Cluster_1_Deposits2_s_fu_536_p3;
    sc_signal< sc_lv<1> > tmp_102_1_fu_738_p2;
    sc_signal< sc_lv<2> > Cluster_1_Eta17_0_Cl_fu_552_p3;
    sc_signal< sc_lv<2> > Cluster_1_Eta_0_Clus_fu_444_p3;
    sc_signal< sc_lv<2> > Cluster_1_Phi32_0_Cl_fu_568_p3;
    sc_signal< sc_lv<2> > Cluster_1_Phi_0_Clus_fu_460_p3;
    sc_signal< sc_lv<16> > Cluster_1_Deposits5_fu_482_p3;
    sc_signal< sc_lv<16> > Cluster_1_Deposits3_s_fu_590_p3;
    sc_signal< sc_lv<1> > tmp_107_1_fu_768_p2;
    sc_signal< sc_lv<2> > Cluster_1_Eta18_0_Cl_fu_606_p3;
    sc_signal< sc_lv<2> > Cluster_1_Eta16_0_Cl_fu_498_p3;
    sc_signal< sc_lv<2> > Cluster_1_Phi33_0_Cl_fu_622_p3;
    sc_signal< sc_lv<2> > Cluster_1_Phi31_0_Cl_fu_514_p3;
    sc_signal< sc_lv<16> > Cluster_1_Deposits2_2_fu_636_p3;
    sc_signal< sc_lv<16> > Cluster_1_Deposits3_2_fu_690_p3;
    sc_signal< sc_lv<1> > tmp_9_fu_798_p2;
    sc_signal< sc_lv<2> > Cluster_1_Eta18_1_Cl_fu_706_p3;
    sc_signal< sc_lv<2> > Cluster_1_Eta17_1_Cl_fu_652_p3;
    sc_signal< sc_lv<2> > Cluster_1_Eta16_2_Cl_fu_804_p3;
    sc_signal< sc_lv<2> > Cluster_1_Eta_2_Clus_fu_816_p3;
    sc_signal< sc_lv<2> > Cluster_1_Phi33_1_Cl_fu_722_p3;
    sc_signal< sc_lv<2> > Cluster_1_Phi32_1_Cl_fu_668_p3;
    sc_signal< sc_lv<2> > Cluster_1_Phi31_2_Cl_fu_828_p3;
    sc_signal< sc_lv<2> > Cluster_1_Phi_2_Clus_fu_840_p3;
    sc_signal< sc_lv<16> > Cluster_1_Deposits_1_9_fu_644_p3;
    sc_signal< sc_lv<16> > Cluster_1_Deposits12_4_fu_698_p3;
    sc_signal< sc_lv<1> > tmp_112_1_fu_852_p2;
    sc_signal< sc_lv<2> > Cluster_1_Eta16_1_Cl_fu_714_p3;
    sc_signal< sc_lv<2> > Cluster_1_Eta_1_Clus_fu_660_p3;
    sc_signal< sc_lv<2> > Cluster_1_Eta18_2_Cl_fu_858_p3;
    sc_signal< sc_lv<2> > Cluster_1_Eta17_2_Cl_fu_870_p3;
    sc_signal< sc_lv<2> > Cluster_1_Phi31_1_Cl_fu_730_p3;
    sc_signal< sc_lv<2> > Cluster_1_Phi_1_Clus_fu_676_p3;
    sc_signal< sc_lv<2> > Cluster_1_Phi33_2_Cl_fu_882_p3;
    sc_signal< sc_lv<2> > Cluster_1_Phi32_2_Cl_fu_894_p3;
    sc_signal< sc_lv<16> > Cluster_1_Deposits6_2_fu_744_p3;
    sc_signal< sc_lv<16> > Cluster_1_Deposits7_2_fu_774_p3;
    sc_signal< sc_lv<1> > tmp_112_2_fu_906_p2;
    sc_signal< sc_lv<2> > Cluster_1_Eta22_1_Cl_fu_782_p3;
    sc_signal< sc_lv<2> > Cluster_1_Eta21_1_Cl_fu_752_p3;
    sc_signal< sc_lv<2> > Cluster_1_Eta2025_2_s_fu_912_p3;
    sc_signal< sc_lv<2> > Cluster_1_Phi3744_1_s_fu_790_p3;
    sc_signal< sc_lv<2> > Cluster_1_Phi36_1_Cl_fu_760_p3;
    sc_signal< sc_lv<2> > Cluster_1_Phi35_2_Cl_fu_924_p3;
    sc_signal< sc_lv<16> > Cluster_1_Eta16_2_Cl_1_fu_812_p1;
    sc_signal< sc_lv<16> > Cluster_1_Eta_2_Clus_1_fu_824_p1;
    sc_signal< sc_lv<16> > Cluster_1_Eta18_2_Cl_1_fu_866_p1;
    sc_signal< sc_lv<16> > Cluster_1_Eta17_2_Cl_1_fu_878_p1;
    sc_signal< sc_lv<16> > Cluster_1_Eta2025_2_1_fu_920_p1;
    sc_signal< sc_lv<16> > Cluster_1_Phi31_2_Cl_1_fu_836_p1;
    sc_signal< sc_lv<16> > Cluster_1_Phi_2_Clus_1_fu_848_p1;
    sc_signal< sc_lv<16> > Cluster_1_Phi33_2_Cl_1_fu_890_p1;
    sc_signal< sc_lv<16> > Cluster_1_Phi32_2_Cl_1_fu_902_p1;
    sc_signal< sc_lv<16> > Cluster_1_Phi35_2_Cl_1_fu_932_p1;
    static const bool ap_const_boolean_1;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    // Thread declarations
    void thread_Cluster_1_Deposits12_4_fu_698_p3();
    void thread_Cluster_1_Deposits2_2_fu_636_p3();
    void thread_Cluster_1_Deposits2_s_fu_536_p3();
    void thread_Cluster_1_Deposits3_2_fu_690_p3();
    void thread_Cluster_1_Deposits3_s_fu_590_p3();
    void thread_Cluster_1_Deposits4_s_fu_420_p3();
    void thread_Cluster_1_Deposits5_fu_482_p3();
    void thread_Cluster_1_Deposits5_s_fu_474_p3();
    void thread_Cluster_1_Deposits6_2_fu_744_p3();
    void thread_Cluster_1_Deposits6_s_fu_528_p3();
    void thread_Cluster_1_Deposits7_2_fu_774_p3();
    void thread_Cluster_1_Deposits7_s_fu_582_p3();
    void thread_Cluster_1_Deposits_1_9_fu_644_p3();
    void thread_Cluster_1_Deposits_fu_428_p3();
    void thread_Cluster_1_Eta16_0_Cl_fu_498_p3();
    void thread_Cluster_1_Eta16_1_Cl_fu_714_p3();
    void thread_Cluster_1_Eta16_2_Cl_1_fu_812_p1();
    void thread_Cluster_1_Eta16_2_Cl_fu_804_p3();
    void thread_Cluster_1_Eta17_0_Cl_fu_552_p3();
    void thread_Cluster_1_Eta17_1_Cl_fu_652_p3();
    void thread_Cluster_1_Eta17_2_Cl_1_fu_878_p1();
    void thread_Cluster_1_Eta17_2_Cl_fu_870_p3();
    void thread_Cluster_1_Eta18_0_Cl_fu_606_p3();
    void thread_Cluster_1_Eta18_1_Cl_fu_706_p3();
    void thread_Cluster_1_Eta18_2_Cl_1_fu_866_p1();
    void thread_Cluster_1_Eta18_2_Cl_fu_858_p3();
    void thread_Cluster_1_Eta19_0_Cl_fu_436_p3();
    void thread_Cluster_1_Eta2025_0_s_fu_490_p3();
    void thread_Cluster_1_Eta2025_2_1_fu_920_p1();
    void thread_Cluster_1_Eta2025_2_s_fu_912_p3();
    void thread_Cluster_1_Eta21_0_Cl_fu_544_p3();
    void thread_Cluster_1_Eta21_1_Cl_fu_752_p3();
    void thread_Cluster_1_Eta22_0_Cl_fu_598_p3();
    void thread_Cluster_1_Eta22_1_Cl_fu_782_p3();
    void thread_Cluster_1_Eta_0_Clus_fu_444_p3();
    void thread_Cluster_1_Eta_1_Clus_fu_660_p3();
    void thread_Cluster_1_Eta_2_Clus_1_fu_824_p1();
    void thread_Cluster_1_Eta_2_Clus_fu_816_p3();
    void thread_Cluster_1_Phi31_0_Cl_fu_514_p3();
    void thread_Cluster_1_Phi31_1_Cl_fu_730_p3();
    void thread_Cluster_1_Phi31_2_Cl_1_fu_836_p1();
    void thread_Cluster_1_Phi31_2_Cl_fu_828_p3();
    void thread_Cluster_1_Phi32_0_Cl_fu_568_p3();
    void thread_Cluster_1_Phi32_1_Cl_fu_668_p3();
    void thread_Cluster_1_Phi32_2_Cl_1_fu_902_p1();
    void thread_Cluster_1_Phi32_2_Cl_fu_894_p3();
    void thread_Cluster_1_Phi33_0_Cl_fu_622_p3();
    void thread_Cluster_1_Phi33_1_Cl_fu_722_p3();
    void thread_Cluster_1_Phi33_2_Cl_1_fu_890_p1();
    void thread_Cluster_1_Phi33_2_Cl_fu_882_p3();
    void thread_Cluster_1_Phi34_0_Cl_fu_452_p3();
    void thread_Cluster_1_Phi35_0_Cl_fu_506_p3();
    void thread_Cluster_1_Phi35_2_Cl_1_fu_932_p1();
    void thread_Cluster_1_Phi35_2_Cl_fu_924_p3();
    void thread_Cluster_1_Phi36_0_Cl_fu_560_p3();
    void thread_Cluster_1_Phi36_1_Cl_fu_760_p3();
    void thread_Cluster_1_Phi3744_0_s_fu_614_p3();
    void thread_Cluster_1_Phi3744_1_s_fu_790_p3();
    void thread_Cluster_1_Phi_0_Clus_fu_460_p3();
    void thread_Cluster_1_Phi_1_Clus_fu_676_p3();
    void thread_Cluster_1_Phi_2_Clus_1_fu_848_p1();
    void thread_Cluster_1_Phi_2_Clus_fu_840_p3();
    void thread_ap_return_0();
    void thread_ap_return_1();
    void thread_ap_return_2();
    void thread_ap_return_3();
    void thread_ap_return_4();
    void thread_ap_return_5();
    void thread_ap_return_6();
    void thread_ap_return_7();
    void thread_ap_return_8();
    void thread_ap_return_9();
    void thread_p_read12_read4_fu_300_p3();
    void thread_p_read13_read5_fu_330_p3();
    void thread_p_read14_read6_fu_360_p3();
    void thread_p_read15_read7_fu_390_p3();
    void thread_p_read28_read_fu_308_p3();
    void thread_p_read29_read_fu_338_p3();
    void thread_p_read30_read_fu_368_p3();
    void thread_p_read31_read_fu_398_p3();
    void thread_p_read44_read_fu_316_p3();
    void thread_p_read45_read_fu_346_p3();
    void thread_p_read46_read_fu_376_p3();
    void thread_p_read47_read_fu_406_p3();
    void thread_tmp_102_1_fu_738_p2();
    void thread_tmp_107_1_fu_768_p2();
    void thread_tmp_112_1_fu_852_p2();
    void thread_tmp_112_2_fu_906_p2();
    void thread_tmp_6_fu_414_p2();
    void thread_tmp_7_fu_630_p2();
    void thread_tmp_89_4_fu_294_p2();
    void thread_tmp_89_5_fu_324_p2();
    void thread_tmp_89_6_fu_354_p2();
    void thread_tmp_89_7_fu_384_p2();
    void thread_tmp_8_fu_684_p2();
    void thread_tmp_93_1_fu_468_p2();
    void thread_tmp_93_2_fu_522_p2();
    void thread_tmp_93_3_fu_576_p2();
    void thread_tmp_9_fu_798_p2();
};

}

using namespace ap_rtl;

#endif
