# ==============================================================
# File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
# Version: 2016.3
# Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
# 
# ==============================================================


/opt/Xilinx/Vivado_HLS/2016.3/../../Vivado/2016.3/bin/vivado  -notrace -mode batch -source ipi_example.tcl -tclargs xcku115-flvb2104-2-e ../xilinx_com_hls_TPG_1_0.zip
