# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7vx690tffg1927-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /afs/cern.ch/user/p/psiddire/CMSSW_10_2_2/src/VivadoHLSProjects/HT/MakeHT/solution1/impl/vhdl/project.cache/wt [current_project]
set_property parent.project_path /afs/cern.ch/user/p/psiddire/CMSSW_10_2_2/src/VivadoHLSProjects/HT/MakeHT/solution1/impl/vhdl/project.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  /afs/cern.ch/user/p/psiddire/CMSSW_10_2_2/src/VivadoHLSProjects/HT/MakeHT/solution1/impl/vhdl/MakeHT_rgnETLUT_0.vhd
  /afs/cern.ch/user/p/psiddire/CMSSW_10_2_2/src/VivadoHLSProjects/HT/MakeHT/solution1/impl/vhdl/MakeHT_rgnETLUT_1.vhd
  /afs/cern.ch/user/p/psiddire/CMSSW_10_2_2/src/VivadoHLSProjects/HT/MakeHT/solution1/impl/vhdl/MakeHT_rgnETLUT_2.vhd
  /afs/cern.ch/user/p/psiddire/CMSSW_10_2_2/src/VivadoHLSProjects/HT/MakeHT/solution1/impl/vhdl/MakeHT_rgnETLUT_3.vhd
  /afs/cern.ch/user/p/psiddire/CMSSW_10_2_2/src/VivadoHLSProjects/HT/MakeHT/solution1/impl/vhdl/MakeHT_rgnETLUT_4.vhd
  /afs/cern.ch/user/p/psiddire/CMSSW_10_2_2/src/VivadoHLSProjects/HT/MakeHT/solution1/impl/vhdl/MakeHT_rgnETLUT_5.vhd
  /afs/cern.ch/user/p/psiddire/CMSSW_10_2_2/src/VivadoHLSProjects/HT/MakeHT/solution1/impl/vhdl/MakeHT_rgnETLUT_6.vhd
  /afs/cern.ch/user/p/psiddire/CMSSW_10_2_2/src/VivadoHLSProjects/HT/MakeHT/solution1/impl/vhdl/MakeHT_rgnETLUT_7.vhd
  /afs/cern.ch/user/p/psiddire/CMSSW_10_2_2/src/VivadoHLSProjects/HT/MakeHT/solution1/impl/vhdl/MakeHT_rgnETLUT_8.vhd
  /afs/cern.ch/user/p/psiddire/CMSSW_10_2_2/src/VivadoHLSProjects/HT/MakeHT/solution1/impl/vhdl/MakeHT_rgnETLUT_9.vhd
  /afs/cern.ch/user/p/psiddire/CMSSW_10_2_2/src/VivadoHLSProjects/HT/MakeHT/solution1/impl/vhdl/MakeHT_rgnETLUT_10.vhd
  /afs/cern.ch/user/p/psiddire/CMSSW_10_2_2/src/VivadoHLSProjects/HT/MakeHT/solution1/impl/vhdl/MakeHT_rgnETLUT_11.vhd
  /afs/cern.ch/user/p/psiddire/CMSSW_10_2_2/src/VivadoHLSProjects/HT/MakeHT/solution1/impl/vhdl/MakeHT_rgnETLUT_12.vhd
  /afs/cern.ch/user/p/psiddire/CMSSW_10_2_2/src/VivadoHLSProjects/HT/MakeHT/solution1/impl/vhdl/MakeHT_rgnETLUT_13.vhd
  /afs/cern.ch/user/p/psiddire/CMSSW_10_2_2/src/VivadoHLSProjects/HT/MakeHT/solution1/impl/vhdl/MakeHT.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /afs/cern.ch/user/p/psiddire/CMSSW_10_2_2/src/VivadoHLSProjects/HT/MakeHT/solution1/impl/vhdl/MakeHT.xdc
set_property used_in_implementation false [get_files /afs/cern.ch/user/p/psiddire/CMSSW_10_2_2/src/VivadoHLSProjects/HT/MakeHT/solution1/impl/vhdl/MakeHT.xdc]


synth_design -top MakeHT -part xc7vx690tffg1927-2 -no_iobuf -mode out_of_context


write_checkpoint -force -noxdef MakeHT.dcp

catch { report_utilization -file MakeHT_utilization_synth.rpt -pb MakeHT_utilization_synth.pb }
