// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// ==============================================================

extern void AESL_WRAP_TowerPeaks (
unsigned short towerET[17][4],
unsigned short TowerPhi[30],
unsigned short TowerEta[30]);
