-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2016.4
-- Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity bitonic_1_8 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    Cluster_1_Deposits_0 : IN STD_LOGIC_VECTOR (15 downto 0);
    Cluster_1_Deposits_1 : IN STD_LOGIC_VECTOR (15 downto 0);
    Cluster_1_Deposits_2 : IN STD_LOGIC_VECTOR (15 downto 0);
    Cluster_1_Deposits_3 : IN STD_LOGIC_VECTOR (15 downto 0);
    Cluster_1_Deposits_4 : IN STD_LOGIC_VECTOR (15 downto 0);
    Cluster_1_Deposits_5 : IN STD_LOGIC_VECTOR (15 downto 0);
    Cluster_1_Deposits_6 : IN STD_LOGIC_VECTOR (15 downto 0);
    Cluster_1_Deposits_7 : IN STD_LOGIC_VECTOR (15 downto 0);
    Cluster_1_Deposits_8 : IN STD_LOGIC_VECTOR (15 downto 0);
    Cluster_1_Deposits_9 : IN STD_LOGIC_VECTOR (15 downto 0);
    Cluster_1_Deposits_1_3 : IN STD_LOGIC_VECTOR (15 downto 0);
    Cluster_1_Deposits_1_4 : IN STD_LOGIC_VECTOR (15 downto 0);
    Cluster_1_Eta_0_rea : IN STD_LOGIC_VECTOR (1 downto 0);
    Cluster_1_Eta_1_rea : IN STD_LOGIC_VECTOR (1 downto 0);
    Cluster_1_Eta_2_rea : IN STD_LOGIC_VECTOR (1 downto 0);
    Cluster_1_Eta_3_rea : IN STD_LOGIC_VECTOR (1 downto 0);
    Cluster_1_Eta_4_rea : IN STD_LOGIC_VECTOR (1 downto 0);
    Cluster_1_Eta_5_rea : IN STD_LOGIC_VECTOR (1 downto 0);
    Cluster_1_Eta_6_rea : IN STD_LOGIC_VECTOR (1 downto 0);
    Cluster_1_Eta_7_rea : IN STD_LOGIC_VECTOR (1 downto 0);
    Cluster_1_Eta_8_rea : IN STD_LOGIC_VECTOR (1 downto 0);
    Cluster_1_Eta_9_rea : IN STD_LOGIC_VECTOR (1 downto 0);
    Cluster_1_Eta_10_re : IN STD_LOGIC_VECTOR (1 downto 0);
    Cluster_1_Eta_11_re : IN STD_LOGIC_VECTOR (1 downto 0);
    Cluster_1_Phi_0_rea : IN STD_LOGIC_VECTOR (0 downto 0);
    Cluster_1_Phi_1_rea : IN STD_LOGIC_VECTOR (0 downto 0);
    Cluster_1_Phi_2_rea : IN STD_LOGIC_VECTOR (0 downto 0);
    Cluster_1_Phi_3_rea : IN STD_LOGIC_VECTOR (0 downto 0);
    Cluster_1_Phi_4_rea : IN STD_LOGIC_VECTOR (1 downto 0);
    Cluster_1_Phi_5_rea : IN STD_LOGIC_VECTOR (1 downto 0);
    Cluster_1_Phi_6_rea : IN STD_LOGIC_VECTOR (1 downto 0);
    Cluster_1_Phi_7_rea : IN STD_LOGIC_VECTOR (1 downto 0);
    Cluster_1_Phi_8_rea : IN STD_LOGIC_VECTOR (1 downto 0);
    Cluster_1_Phi_9_rea : IN STD_LOGIC_VECTOR (1 downto 0);
    Cluster_1_Phi_10_re : IN STD_LOGIC_VECTOR (1 downto 0);
    Cluster_1_Phi_11_re : IN STD_LOGIC_VECTOR (1 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_4 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_5 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_6 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_7 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_8 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_9 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_ce : IN STD_LOGIC );
end;


architecture behav of bitonic_1_8 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0);
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal Cluster_1_Deposits12_2_fu_990_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal Cluster_1_Deposits12_2_reg_1308 : STD_LOGIC_VECTOR (15 downto 0);
    signal Cluster_1_Deposits_1_8_fu_998_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal Cluster_1_Deposits_1_8_reg_1313 : STD_LOGIC_VECTOR (15 downto 0);
    signal Cluster_1_Eta16_1_Cl_fu_1006_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal Cluster_1_Eta16_1_Cl_reg_1318 : STD_LOGIC_VECTOR (1 downto 0);
    signal Cluster_1_Eta_1_Clus_fu_1014_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal Cluster_1_Eta_1_Clus_reg_1323 : STD_LOGIC_VECTOR (1 downto 0);
    signal Cluster_1_Phi31_1_Cl_fu_1022_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal Cluster_1_Phi31_1_Cl_reg_1328 : STD_LOGIC_VECTOR (1 downto 0);
    signal Cluster_1_Phi_1_Clus_fu_1030_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal Cluster_1_Phi_1_Clus_reg_1333 : STD_LOGIC_VECTOR (1 downto 0);
    signal Cluster_1_Deposits3_1_fu_1044_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal Cluster_1_Deposits3_1_reg_1338 : STD_LOGIC_VECTOR (15 downto 0);
    signal Cluster_1_Deposits2_1_fu_1052_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal Cluster_1_Deposits2_1_reg_1343 : STD_LOGIC_VECTOR (15 downto 0);
    signal Cluster_1_Eta18_1_Cl_fu_1060_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal Cluster_1_Eta18_1_Cl_reg_1348 : STD_LOGIC_VECTOR (1 downto 0);
    signal Cluster_1_Eta17_1_Cl_fu_1068_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal Cluster_1_Eta17_1_Cl_reg_1353 : STD_LOGIC_VECTOR (1 downto 0);
    signal Cluster_1_Phi33_1_Cl_fu_1076_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal Cluster_1_Phi33_1_Cl_reg_1358 : STD_LOGIC_VECTOR (1 downto 0);
    signal Cluster_1_Phi32_1_Cl_fu_1084_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal Cluster_1_Phi32_1_Cl_reg_1363 : STD_LOGIC_VECTOR (1 downto 0);
    signal Cluster_1_Deposits5_1_fu_1098_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal Cluster_1_Deposits5_1_reg_1368 : STD_LOGIC_VECTOR (15 downto 0);
    signal Cluster_1_Deposits4_1_fu_1106_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal Cluster_1_Deposits4_1_reg_1373 : STD_LOGIC_VECTOR (15 downto 0);
    signal Cluster_1_Eta2025_1_s_fu_1114_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal Cluster_1_Eta2025_1_s_reg_1378 : STD_LOGIC_VECTOR (1 downto 0);
    signal Cluster_1_Eta19_1_Cl_fu_1122_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal Cluster_1_Eta19_1_Cl_reg_1383 : STD_LOGIC_VECTOR (1 downto 0);
    signal Cluster_1_Phi35_1_Cl_fu_1130_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal Cluster_1_Phi35_1_Cl_reg_1388 : STD_LOGIC_VECTOR (1 downto 0);
    signal Cluster_1_Phi34_1_Cl_fu_1138_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal Cluster_1_Phi34_1_Cl_reg_1393 : STD_LOGIC_VECTOR (1 downto 0);
    signal Cluster_1_Deposits7_1_fu_1152_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal Cluster_1_Deposits7_1_reg_1398 : STD_LOGIC_VECTOR (15 downto 0);
    signal Cluster_1_Deposits6_1_fu_1160_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal Cluster_1_Deposits6_1_reg_1403 : STD_LOGIC_VECTOR (15 downto 0);
    signal Cluster_1_Eta22_1_Cl_fu_1168_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal Cluster_1_Eta22_1_Cl_reg_1408 : STD_LOGIC_VECTOR (1 downto 0);
    signal Cluster_1_Eta21_1_Cl_fu_1176_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal Cluster_1_Eta21_1_Cl_reg_1413 : STD_LOGIC_VECTOR (1 downto 0);
    signal Cluster_1_Phi3744_1_s_fu_1184_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal Cluster_1_Phi3744_1_s_reg_1418 : STD_LOGIC_VECTOR (1 downto 0);
    signal Cluster_1_Phi36_1_Cl_fu_1192_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal Cluster_1_Phi36_1_Cl_reg_1423 : STD_LOGIC_VECTOR (1 downto 0);
    signal Cluster_1_Deposits13_1_fu_1206_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal Cluster_1_Deposits13_1_reg_1428 : STD_LOGIC_VECTOR (15 downto 0);
    signal Cluster_1_Deposits12_3_fu_1214_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal Cluster_1_Deposits12_3_reg_1433 : STD_LOGIC_VECTOR (15 downto 0);
    signal Cluster_1_Eta28_1_Cl_fu_1222_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal Cluster_1_Eta28_1_Cl_reg_1438 : STD_LOGIC_VECTOR (1 downto 0);
    signal Cluster_1_Eta27_1_Cl_fu_1230_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal Cluster_1_Eta27_1_Cl_reg_1443 : STD_LOGIC_VECTOR (1 downto 0);
    signal Cluster_1_Phi43_1_Cl_fu_1238_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal Cluster_1_Phi43_1_Cl_reg_1448 : STD_LOGIC_VECTOR (1 downto 0);
    signal Cluster_1_Phi42_1_Cl_fu_1246_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal Cluster_1_Phi42_1_Cl_reg_1453 : STD_LOGIC_VECTOR (1 downto 0);
    signal Cluster_1_Deposits15_1_fu_1260_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal Cluster_1_Deposits15_1_reg_1458 : STD_LOGIC_VECTOR (15 downto 0);
    signal Cluster_1_Deposits14_1_fu_1268_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal Cluster_1_Deposits14_1_reg_1463 : STD_LOGIC_VECTOR (15 downto 0);
    signal Cluster_1_Eta30_1_Cl_fu_1276_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal Cluster_1_Eta30_1_Cl_reg_1468 : STD_LOGIC_VECTOR (1 downto 0);
    signal Cluster_1_Eta29_1_Cl_fu_1284_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal Cluster_1_Eta29_1_Cl_reg_1473 : STD_LOGIC_VECTOR (1 downto 0);
    signal Cluster_1_Phi45_1_Cl_fu_1292_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal Cluster_1_Phi45_1_Cl_reg_1478 : STD_LOGIC_VECTOR (1 downto 0);
    signal Cluster_1_Phi44_1_Cl_fu_1300_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal Cluster_1_Phi44_1_Cl_reg_1483 : STD_LOGIC_VECTOR (1 downto 0);
    signal call_ret_bitonic_1_16_fu_300_ap_return_0 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret_bitonic_1_16_fu_300_ap_return_1 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret_bitonic_1_16_fu_300_ap_return_2 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret_bitonic_1_16_fu_300_ap_return_3 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret_bitonic_1_16_fu_300_ap_return_4 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret_bitonic_1_16_fu_300_ap_return_5 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret_bitonic_1_16_fu_300_ap_return_6 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret_bitonic_1_16_fu_300_ap_return_7 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret_bitonic_1_16_fu_300_ap_return_8 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret_bitonic_1_16_fu_300_ap_return_9 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC_VECTOR (0 downto 0);
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal tmp_s_fu_340_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal Cluster_1_Phi_0_rea_1_fu_378_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_19_1_fu_398_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal Cluster_1_Phi_1_rea_1_fu_436_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_19_2_fu_456_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal Cluster_1_Phi_2_rea_1_fu_494_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_19_3_fu_514_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal Cluster_1_Phi_3_rea_1_fu_552_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_2_fu_572_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_23_1_fu_594_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_23_2_fu_616_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_23_3_fu_638_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_read4_read_fu_346_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read6_read2_fu_462_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_3_fu_660_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_read22_read_fu_478_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_read20_read_fu_362_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_read38_read_fu_498_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_read36_read_fu_382_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_read5_read1_fu_404_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read7_read3_fu_520_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_4_fu_714_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_read23_read_fu_536_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_read21_read_fu_420_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_read39_read_fu_556_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_read37_read_fu_440_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_read_read4_fu_354_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read2_read6_fu_470_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_28_1_fu_768_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_read18_read_fu_486_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_read16_read_fu_370_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_read34_read_fu_506_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_read32_read_fu_390_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_read1_read5_fu_412_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read3_read7_fu_528_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_33_1_fu_822_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_read19_read_fu_544_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_read17_read_fu_428_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_read35_read_fu_564_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_read33_read_fu_448_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_38_1_fu_876_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_read4_fu_622_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_read_fu_578_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_read5_fu_630_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_read1_fu_586_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_43_1_fu_930_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_read6_fu_644_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_read2_fu_600_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_read7_fu_652_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_read3_fu_608_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal Cluster_1_Deposits2_s_fu_666_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal Cluster_1_Deposits3_s_fu_720_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_5_fu_984_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal Cluster_1_Eta18_0_Cl_fu_736_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal Cluster_1_Eta17_0_Cl_fu_682_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal Cluster_1_Phi33_0_Cl_fu_752_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal Cluster_1_Phi32_0_Cl_fu_698_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal Cluster_1_Deposits_fu_674_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal Cluster_1_Deposits1_fu_728_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_48_1_fu_1038_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal Cluster_1_Eta16_0_Cl_fu_744_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal Cluster_1_Eta_0_Clus_fu_690_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal Cluster_1_Phi31_0_Cl_fu_760_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal Cluster_1_Phi_0_Clus_fu_706_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal Cluster_1_Deposits6_s_fu_774_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal Cluster_1_Deposits7_s_fu_828_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_48_2_fu_1092_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal Cluster_1_Eta22_0_Cl_fu_844_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal Cluster_1_Eta21_0_Cl_fu_790_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal Cluster_1_Phi3744_0_s_fu_860_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal Cluster_1_Phi36_0_Cl_fu_806_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal Cluster_1_Deposits4_s_fu_782_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal Cluster_1_Deposits5_s_fu_836_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_48_3_fu_1146_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal Cluster_1_Eta2025_0_s_fu_852_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal Cluster_1_Eta19_0_Cl_fu_798_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal Cluster_1_Phi35_0_Cl_fu_868_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal Cluster_1_Phi34_0_Cl_fu_814_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal Cluster_1_Deposits2_fu_882_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal Cluster_1_Deposits3_fu_936_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_53_2_fu_1200_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal Cluster_1_Eta30_0_Cl_fu_952_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal Cluster_1_Eta29_0_Cl_fu_898_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal Cluster_1_Phi45_0_Cl_fu_968_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal Cluster_1_Phi44_0_Cl_fu_914_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal Cluster_1_Deposits12_1_fu_890_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal Cluster_1_Deposits4_fu_944_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_53_3_fu_1254_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal Cluster_1_Eta28_0_Cl_fu_960_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal Cluster_1_Eta27_0_Cl_fu_906_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal Cluster_1_Phi43_0_Cl_fu_976_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal Cluster_1_Phi42_0_Cl_fu_922_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);

    component bitonic_1_16 IS
    port (
        Cluster_1_Deposits_0 : IN STD_LOGIC_VECTOR (15 downto 0);
        Cluster_1_Deposits_1 : IN STD_LOGIC_VECTOR (15 downto 0);
        Cluster_1_Deposits_2 : IN STD_LOGIC_VECTOR (15 downto 0);
        Cluster_1_Deposits_3 : IN STD_LOGIC_VECTOR (15 downto 0);
        Cluster_1_Deposits_4 : IN STD_LOGIC_VECTOR (15 downto 0);
        Cluster_1_Deposits_5 : IN STD_LOGIC_VECTOR (15 downto 0);
        Cluster_1_Deposits_6 : IN STD_LOGIC_VECTOR (15 downto 0);
        Cluster_1_Deposits_7 : IN STD_LOGIC_VECTOR (15 downto 0);
        Cluster_1_Deposits_1_12 : IN STD_LOGIC_VECTOR (15 downto 0);
        Cluster_1_Deposits_1_13 : IN STD_LOGIC_VECTOR (15 downto 0);
        Cluster_1_Deposits_1_14 : IN STD_LOGIC_VECTOR (15 downto 0);
        Cluster_1_Deposits_1_15 : IN STD_LOGIC_VECTOR (15 downto 0);
        Cluster_1_Eta_0_rea : IN STD_LOGIC_VECTOR (1 downto 0);
        Cluster_1_Eta_1_rea : IN STD_LOGIC_VECTOR (1 downto 0);
        Cluster_1_Eta_2_rea : IN STD_LOGIC_VECTOR (1 downto 0);
        Cluster_1_Eta_3_rea : IN STD_LOGIC_VECTOR (1 downto 0);
        Cluster_1_Eta_4_rea : IN STD_LOGIC_VECTOR (1 downto 0);
        Cluster_1_Eta_5_rea : IN STD_LOGIC_VECTOR (1 downto 0);
        Cluster_1_Eta_6_rea : IN STD_LOGIC_VECTOR (1 downto 0);
        Cluster_1_Eta_7_rea : IN STD_LOGIC_VECTOR (1 downto 0);
        Cluster_1_Eta_12_re : IN STD_LOGIC_VECTOR (1 downto 0);
        Cluster_1_Eta_13_re : IN STD_LOGIC_VECTOR (1 downto 0);
        Cluster_1_Eta_14_re : IN STD_LOGIC_VECTOR (1 downto 0);
        Cluster_1_Eta_15_re : IN STD_LOGIC_VECTOR (1 downto 0);
        Cluster_1_Phi_0_rea : IN STD_LOGIC_VECTOR (1 downto 0);
        Cluster_1_Phi_1_rea : IN STD_LOGIC_VECTOR (1 downto 0);
        Cluster_1_Phi_2_rea : IN STD_LOGIC_VECTOR (1 downto 0);
        Cluster_1_Phi_3_rea : IN STD_LOGIC_VECTOR (1 downto 0);
        Cluster_1_Phi_4_rea : IN STD_LOGIC_VECTOR (1 downto 0);
        Cluster_1_Phi_5_rea : IN STD_LOGIC_VECTOR (1 downto 0);
        Cluster_1_Phi_6_rea : IN STD_LOGIC_VECTOR (1 downto 0);
        Cluster_1_Phi_7_rea : IN STD_LOGIC_VECTOR (1 downto 0);
        Cluster_1_Phi_12_re : IN STD_LOGIC_VECTOR (1 downto 0);
        Cluster_1_Phi_13_re : IN STD_LOGIC_VECTOR (1 downto 0);
        Cluster_1_Phi_14_re : IN STD_LOGIC_VECTOR (1 downto 0);
        Cluster_1_Phi_15_re : IN STD_LOGIC_VECTOR (1 downto 0);
        ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_3 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_4 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_5 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_6 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_7 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_8 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_9 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;



begin
    call_ret_bitonic_1_16_fu_300 : component bitonic_1_16
    port map (
        Cluster_1_Deposits_0 => Cluster_1_Deposits12_2_reg_1308,
        Cluster_1_Deposits_1 => Cluster_1_Deposits_1_8_reg_1313,
        Cluster_1_Deposits_2 => Cluster_1_Deposits3_1_reg_1338,
        Cluster_1_Deposits_3 => Cluster_1_Deposits2_1_reg_1343,
        Cluster_1_Deposits_4 => Cluster_1_Deposits5_1_reg_1368,
        Cluster_1_Deposits_5 => Cluster_1_Deposits4_1_reg_1373,
        Cluster_1_Deposits_6 => Cluster_1_Deposits7_1_reg_1398,
        Cluster_1_Deposits_7 => Cluster_1_Deposits6_1_reg_1403,
        Cluster_1_Deposits_1_12 => Cluster_1_Deposits13_1_reg_1428,
        Cluster_1_Deposits_1_13 => Cluster_1_Deposits12_3_reg_1433,
        Cluster_1_Deposits_1_14 => Cluster_1_Deposits15_1_reg_1458,
        Cluster_1_Deposits_1_15 => Cluster_1_Deposits14_1_reg_1463,
        Cluster_1_Eta_0_rea => Cluster_1_Eta16_1_Cl_reg_1318,
        Cluster_1_Eta_1_rea => Cluster_1_Eta_1_Clus_reg_1323,
        Cluster_1_Eta_2_rea => Cluster_1_Eta18_1_Cl_reg_1348,
        Cluster_1_Eta_3_rea => Cluster_1_Eta17_1_Cl_reg_1353,
        Cluster_1_Eta_4_rea => Cluster_1_Eta2025_1_s_reg_1378,
        Cluster_1_Eta_5_rea => Cluster_1_Eta19_1_Cl_reg_1383,
        Cluster_1_Eta_6_rea => Cluster_1_Eta22_1_Cl_reg_1408,
        Cluster_1_Eta_7_rea => Cluster_1_Eta21_1_Cl_reg_1413,
        Cluster_1_Eta_12_re => Cluster_1_Eta28_1_Cl_reg_1438,
        Cluster_1_Eta_13_re => Cluster_1_Eta27_1_Cl_reg_1443,
        Cluster_1_Eta_14_re => Cluster_1_Eta30_1_Cl_reg_1468,
        Cluster_1_Eta_15_re => Cluster_1_Eta29_1_Cl_reg_1473,
        Cluster_1_Phi_0_rea => Cluster_1_Phi31_1_Cl_reg_1328,
        Cluster_1_Phi_1_rea => Cluster_1_Phi_1_Clus_reg_1333,
        Cluster_1_Phi_2_rea => Cluster_1_Phi33_1_Cl_reg_1358,
        Cluster_1_Phi_3_rea => Cluster_1_Phi32_1_Cl_reg_1363,
        Cluster_1_Phi_4_rea => Cluster_1_Phi35_1_Cl_reg_1388,
        Cluster_1_Phi_5_rea => Cluster_1_Phi34_1_Cl_reg_1393,
        Cluster_1_Phi_6_rea => Cluster_1_Phi3744_1_s_reg_1418,
        Cluster_1_Phi_7_rea => Cluster_1_Phi36_1_Cl_reg_1423,
        Cluster_1_Phi_12_re => Cluster_1_Phi43_1_Cl_reg_1448,
        Cluster_1_Phi_13_re => Cluster_1_Phi42_1_Cl_reg_1453,
        Cluster_1_Phi_14_re => Cluster_1_Phi45_1_Cl_reg_1478,
        Cluster_1_Phi_15_re => Cluster_1_Phi44_1_Cl_reg_1483,
        ap_return_0 => call_ret_bitonic_1_16_fu_300_ap_return_0,
        ap_return_1 => call_ret_bitonic_1_16_fu_300_ap_return_1,
        ap_return_2 => call_ret_bitonic_1_16_fu_300_ap_return_2,
        ap_return_3 => call_ret_bitonic_1_16_fu_300_ap_return_3,
        ap_return_4 => call_ret_bitonic_1_16_fu_300_ap_return_4,
        ap_return_5 => call_ret_bitonic_1_16_fu_300_ap_return_5,
        ap_return_6 => call_ret_bitonic_1_16_fu_300_ap_return_6,
        ap_return_7 => call_ret_bitonic_1_16_fu_300_ap_return_7,
        ap_return_8 => call_ret_bitonic_1_16_fu_300_ap_return_8,
        ap_return_9 => call_ret_bitonic_1_16_fu_300_ap_return_9);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_CS_fsm_state1 = ap_const_lv1_1) and (ap_const_logic_1 = ap_ce) and not((ap_start = ap_const_logic_0)))) then
                Cluster_1_Deposits12_2_reg_1308 <= Cluster_1_Deposits12_2_fu_990_p3;
                Cluster_1_Deposits12_3_reg_1433 <= Cluster_1_Deposits12_3_fu_1214_p3;
                Cluster_1_Deposits13_1_reg_1428 <= Cluster_1_Deposits13_1_fu_1206_p3;
                Cluster_1_Deposits14_1_reg_1463 <= Cluster_1_Deposits14_1_fu_1268_p3;
                Cluster_1_Deposits15_1_reg_1458 <= Cluster_1_Deposits15_1_fu_1260_p3;
                Cluster_1_Deposits2_1_reg_1343 <= Cluster_1_Deposits2_1_fu_1052_p3;
                Cluster_1_Deposits3_1_reg_1338 <= Cluster_1_Deposits3_1_fu_1044_p3;
                Cluster_1_Deposits4_1_reg_1373 <= Cluster_1_Deposits4_1_fu_1106_p3;
                Cluster_1_Deposits5_1_reg_1368 <= Cluster_1_Deposits5_1_fu_1098_p3;
                Cluster_1_Deposits6_1_reg_1403 <= Cluster_1_Deposits6_1_fu_1160_p3;
                Cluster_1_Deposits7_1_reg_1398 <= Cluster_1_Deposits7_1_fu_1152_p3;
                Cluster_1_Deposits_1_8_reg_1313 <= Cluster_1_Deposits_1_8_fu_998_p3;
                Cluster_1_Eta16_1_Cl_reg_1318 <= Cluster_1_Eta16_1_Cl_fu_1006_p3;
                Cluster_1_Eta17_1_Cl_reg_1353 <= Cluster_1_Eta17_1_Cl_fu_1068_p3;
                Cluster_1_Eta18_1_Cl_reg_1348 <= Cluster_1_Eta18_1_Cl_fu_1060_p3;
                Cluster_1_Eta19_1_Cl_reg_1383 <= Cluster_1_Eta19_1_Cl_fu_1122_p3;
                Cluster_1_Eta2025_1_s_reg_1378 <= Cluster_1_Eta2025_1_s_fu_1114_p3;
                Cluster_1_Eta21_1_Cl_reg_1413 <= Cluster_1_Eta21_1_Cl_fu_1176_p3;
                Cluster_1_Eta22_1_Cl_reg_1408 <= Cluster_1_Eta22_1_Cl_fu_1168_p3;
                Cluster_1_Eta27_1_Cl_reg_1443 <= Cluster_1_Eta27_1_Cl_fu_1230_p3;
                Cluster_1_Eta28_1_Cl_reg_1438 <= Cluster_1_Eta28_1_Cl_fu_1222_p3;
                Cluster_1_Eta29_1_Cl_reg_1473 <= Cluster_1_Eta29_1_Cl_fu_1284_p3;
                Cluster_1_Eta30_1_Cl_reg_1468 <= Cluster_1_Eta30_1_Cl_fu_1276_p3;
                Cluster_1_Eta_1_Clus_reg_1323 <= Cluster_1_Eta_1_Clus_fu_1014_p3;
                Cluster_1_Phi31_1_Cl_reg_1328 <= Cluster_1_Phi31_1_Cl_fu_1022_p3;
                Cluster_1_Phi32_1_Cl_reg_1363 <= Cluster_1_Phi32_1_Cl_fu_1084_p3;
                Cluster_1_Phi33_1_Cl_reg_1358 <= Cluster_1_Phi33_1_Cl_fu_1076_p3;
                Cluster_1_Phi34_1_Cl_reg_1393 <= Cluster_1_Phi34_1_Cl_fu_1138_p3;
                Cluster_1_Phi35_1_Cl_reg_1388 <= Cluster_1_Phi35_1_Cl_fu_1130_p3;
                Cluster_1_Phi36_1_Cl_reg_1423 <= Cluster_1_Phi36_1_Cl_fu_1192_p3;
                Cluster_1_Phi3744_1_s_reg_1418 <= Cluster_1_Phi3744_1_s_fu_1184_p3;
                Cluster_1_Phi42_1_Cl_reg_1453 <= Cluster_1_Phi42_1_Cl_fu_1246_p3;
                Cluster_1_Phi43_1_Cl_reg_1448 <= Cluster_1_Phi43_1_Cl_fu_1238_p3;
                Cluster_1_Phi44_1_Cl_reg_1483 <= Cluster_1_Phi44_1_Cl_fu_1300_p3;
                Cluster_1_Phi45_1_Cl_reg_1478 <= Cluster_1_Phi45_1_Cl_fu_1292_p3;
                Cluster_1_Phi_1_Clus_reg_1333 <= Cluster_1_Phi_1_Clus_fu_1030_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_ce)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_ce) and not((ap_start = ap_const_logic_0)))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if ((ap_const_logic_1 = ap_ce)) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    Cluster_1_Deposits12_1_fu_890_p3 <= 
        Cluster_1_Deposits_8 when (tmp_38_1_fu_876_p2(0) = '1') else 
        Cluster_1_Deposits_1_3;
    Cluster_1_Deposits12_2_fu_990_p3 <= 
        Cluster_1_Deposits3_s_fu_720_p3 when (tmp_5_fu_984_p2(0) = '1') else 
        Cluster_1_Deposits2_s_fu_666_p3;
    Cluster_1_Deposits12_3_fu_1214_p3 <= 
        Cluster_1_Deposits2_fu_882_p3 when (tmp_53_2_fu_1200_p2(0) = '1') else 
        Cluster_1_Deposits3_fu_936_p3;
    Cluster_1_Deposits13_1_fu_1206_p3 <= 
        Cluster_1_Deposits3_fu_936_p3 when (tmp_53_2_fu_1200_p2(0) = '1') else 
        Cluster_1_Deposits2_fu_882_p3;
    Cluster_1_Deposits14_1_fu_1268_p3 <= 
        Cluster_1_Deposits12_1_fu_890_p3 when (tmp_53_3_fu_1254_p2(0) = '1') else 
        Cluster_1_Deposits4_fu_944_p3;
    Cluster_1_Deposits15_1_fu_1260_p3 <= 
        Cluster_1_Deposits4_fu_944_p3 when (tmp_53_3_fu_1254_p2(0) = '1') else 
        Cluster_1_Deposits12_1_fu_890_p3;
    Cluster_1_Deposits1_fu_728_p3 <= 
        p_read5_read1_fu_404_p3 when (tmp_4_fu_714_p2(0) = '1') else 
        p_read7_read3_fu_520_p3;
    Cluster_1_Deposits2_1_fu_1052_p3 <= 
        Cluster_1_Deposits_fu_674_p3 when (tmp_48_1_fu_1038_p2(0) = '1') else 
        Cluster_1_Deposits1_fu_728_p3;
    Cluster_1_Deposits2_fu_882_p3 <= 
        Cluster_1_Deposits_1_3 when (tmp_38_1_fu_876_p2(0) = '1') else 
        Cluster_1_Deposits_8;
    Cluster_1_Deposits2_s_fu_666_p3 <= 
        p_read6_read2_fu_462_p3 when (tmp_3_fu_660_p2(0) = '1') else 
        p_read4_read_fu_346_p3;
    Cluster_1_Deposits3_1_fu_1044_p3 <= 
        Cluster_1_Deposits1_fu_728_p3 when (tmp_48_1_fu_1038_p2(0) = '1') else 
        Cluster_1_Deposits_fu_674_p3;
    Cluster_1_Deposits3_fu_936_p3 <= 
        Cluster_1_Deposits_1_4 when (tmp_43_1_fu_930_p2(0) = '1') else 
        Cluster_1_Deposits_9;
    Cluster_1_Deposits3_s_fu_720_p3 <= 
        p_read7_read3_fu_520_p3 when (tmp_4_fu_714_p2(0) = '1') else 
        p_read5_read1_fu_404_p3;
    Cluster_1_Deposits4_1_fu_1106_p3 <= 
        Cluster_1_Deposits6_s_fu_774_p3 when (tmp_48_2_fu_1092_p2(0) = '1') else 
        Cluster_1_Deposits7_s_fu_828_p3;
    Cluster_1_Deposits4_fu_944_p3 <= 
        Cluster_1_Deposits_9 when (tmp_43_1_fu_930_p2(0) = '1') else 
        Cluster_1_Deposits_1_4;
    Cluster_1_Deposits4_s_fu_782_p3 <= 
        p_read_read4_fu_354_p3 when (tmp_28_1_fu_768_p2(0) = '1') else 
        p_read2_read6_fu_470_p3;
    Cluster_1_Deposits5_1_fu_1098_p3 <= 
        Cluster_1_Deposits7_s_fu_828_p3 when (tmp_48_2_fu_1092_p2(0) = '1') else 
        Cluster_1_Deposits6_s_fu_774_p3;
    Cluster_1_Deposits5_s_fu_836_p3 <= 
        p_read1_read5_fu_412_p3 when (tmp_33_1_fu_822_p2(0) = '1') else 
        p_read3_read7_fu_528_p3;
    Cluster_1_Deposits6_1_fu_1160_p3 <= 
        Cluster_1_Deposits4_s_fu_782_p3 when (tmp_48_3_fu_1146_p2(0) = '1') else 
        Cluster_1_Deposits5_s_fu_836_p3;
    Cluster_1_Deposits6_s_fu_774_p3 <= 
        p_read2_read6_fu_470_p3 when (tmp_28_1_fu_768_p2(0) = '1') else 
        p_read_read4_fu_354_p3;
    Cluster_1_Deposits7_1_fu_1152_p3 <= 
        Cluster_1_Deposits5_s_fu_836_p3 when (tmp_48_3_fu_1146_p2(0) = '1') else 
        Cluster_1_Deposits4_s_fu_782_p3;
    Cluster_1_Deposits7_s_fu_828_p3 <= 
        p_read3_read7_fu_528_p3 when (tmp_33_1_fu_822_p2(0) = '1') else 
        p_read1_read5_fu_412_p3;
    Cluster_1_Deposits_1_8_fu_998_p3 <= 
        Cluster_1_Deposits2_s_fu_666_p3 when (tmp_5_fu_984_p2(0) = '1') else 
        Cluster_1_Deposits3_s_fu_720_p3;
    Cluster_1_Deposits_fu_674_p3 <= 
        p_read4_read_fu_346_p3 when (tmp_3_fu_660_p2(0) = '1') else 
        p_read6_read2_fu_462_p3;
    Cluster_1_Eta16_0_Cl_fu_744_p3 <= 
        p_read21_read_fu_420_p3 when (tmp_4_fu_714_p2(0) = '1') else 
        p_read23_read_fu_536_p3;
    Cluster_1_Eta16_1_Cl_fu_1006_p3 <= 
        Cluster_1_Eta18_0_Cl_fu_736_p3 when (tmp_5_fu_984_p2(0) = '1') else 
        Cluster_1_Eta17_0_Cl_fu_682_p3;
    Cluster_1_Eta17_0_Cl_fu_682_p3 <= 
        p_read22_read_fu_478_p3 when (tmp_3_fu_660_p2(0) = '1') else 
        p_read20_read_fu_362_p3;
    Cluster_1_Eta17_1_Cl_fu_1068_p3 <= 
        Cluster_1_Eta_0_Clus_fu_690_p3 when (tmp_48_1_fu_1038_p2(0) = '1') else 
        Cluster_1_Eta16_0_Cl_fu_744_p3;
    Cluster_1_Eta18_0_Cl_fu_736_p3 <= 
        p_read23_read_fu_536_p3 when (tmp_4_fu_714_p2(0) = '1') else 
        p_read21_read_fu_420_p3;
    Cluster_1_Eta18_1_Cl_fu_1060_p3 <= 
        Cluster_1_Eta16_0_Cl_fu_744_p3 when (tmp_48_1_fu_1038_p2(0) = '1') else 
        Cluster_1_Eta_0_Clus_fu_690_p3;
    Cluster_1_Eta19_0_Cl_fu_798_p3 <= 
        p_read16_read_fu_370_p3 when (tmp_28_1_fu_768_p2(0) = '1') else 
        p_read18_read_fu_486_p3;
    Cluster_1_Eta19_1_Cl_fu_1122_p3 <= 
        Cluster_1_Eta21_0_Cl_fu_790_p3 when (tmp_48_2_fu_1092_p2(0) = '1') else 
        Cluster_1_Eta22_0_Cl_fu_844_p3;
    Cluster_1_Eta2025_0_s_fu_852_p3 <= 
        p_read17_read_fu_428_p3 when (tmp_33_1_fu_822_p2(0) = '1') else 
        p_read19_read_fu_544_p3;
    Cluster_1_Eta2025_1_s_fu_1114_p3 <= 
        Cluster_1_Eta22_0_Cl_fu_844_p3 when (tmp_48_2_fu_1092_p2(0) = '1') else 
        Cluster_1_Eta21_0_Cl_fu_790_p3;
    Cluster_1_Eta21_0_Cl_fu_790_p3 <= 
        p_read18_read_fu_486_p3 when (tmp_28_1_fu_768_p2(0) = '1') else 
        p_read16_read_fu_370_p3;
    Cluster_1_Eta21_1_Cl_fu_1176_p3 <= 
        Cluster_1_Eta19_0_Cl_fu_798_p3 when (tmp_48_3_fu_1146_p2(0) = '1') else 
        Cluster_1_Eta2025_0_s_fu_852_p3;
    Cluster_1_Eta22_0_Cl_fu_844_p3 <= 
        p_read19_read_fu_544_p3 when (tmp_33_1_fu_822_p2(0) = '1') else 
        p_read17_read_fu_428_p3;
    Cluster_1_Eta22_1_Cl_fu_1168_p3 <= 
        Cluster_1_Eta2025_0_s_fu_852_p3 when (tmp_48_3_fu_1146_p2(0) = '1') else 
        Cluster_1_Eta19_0_Cl_fu_798_p3;
    Cluster_1_Eta27_0_Cl_fu_906_p3 <= 
        p_read_fu_578_p3 when (tmp_38_1_fu_876_p2(0) = '1') else 
        p_read4_fu_622_p3;
    Cluster_1_Eta27_1_Cl_fu_1230_p3 <= 
        Cluster_1_Eta29_0_Cl_fu_898_p3 when (tmp_53_2_fu_1200_p2(0) = '1') else 
        Cluster_1_Eta30_0_Cl_fu_952_p3;
    Cluster_1_Eta28_0_Cl_fu_960_p3 <= 
        p_read2_fu_600_p3 when (tmp_43_1_fu_930_p2(0) = '1') else 
        p_read6_fu_644_p3;
    Cluster_1_Eta28_1_Cl_fu_1222_p3 <= 
        Cluster_1_Eta30_0_Cl_fu_952_p3 when (tmp_53_2_fu_1200_p2(0) = '1') else 
        Cluster_1_Eta29_0_Cl_fu_898_p3;
    Cluster_1_Eta29_0_Cl_fu_898_p3 <= 
        p_read4_fu_622_p3 when (tmp_38_1_fu_876_p2(0) = '1') else 
        p_read_fu_578_p3;
    Cluster_1_Eta29_1_Cl_fu_1284_p3 <= 
        Cluster_1_Eta27_0_Cl_fu_906_p3 when (tmp_53_3_fu_1254_p2(0) = '1') else 
        Cluster_1_Eta28_0_Cl_fu_960_p3;
    Cluster_1_Eta30_0_Cl_fu_952_p3 <= 
        p_read6_fu_644_p3 when (tmp_43_1_fu_930_p2(0) = '1') else 
        p_read2_fu_600_p3;
    Cluster_1_Eta30_1_Cl_fu_1276_p3 <= 
        Cluster_1_Eta28_0_Cl_fu_960_p3 when (tmp_53_3_fu_1254_p2(0) = '1') else 
        Cluster_1_Eta27_0_Cl_fu_906_p3;
    Cluster_1_Eta_0_Clus_fu_690_p3 <= 
        p_read20_read_fu_362_p3 when (tmp_3_fu_660_p2(0) = '1') else 
        p_read22_read_fu_478_p3;
    Cluster_1_Eta_1_Clus_fu_1014_p3 <= 
        Cluster_1_Eta17_0_Cl_fu_682_p3 when (tmp_5_fu_984_p2(0) = '1') else 
        Cluster_1_Eta18_0_Cl_fu_736_p3;
    Cluster_1_Phi31_0_Cl_fu_760_p3 <= 
        p_read37_read_fu_440_p3 when (tmp_4_fu_714_p2(0) = '1') else 
        p_read39_read_fu_556_p3;
    Cluster_1_Phi31_1_Cl_fu_1022_p3 <= 
        Cluster_1_Phi33_0_Cl_fu_752_p3 when (tmp_5_fu_984_p2(0) = '1') else 
        Cluster_1_Phi32_0_Cl_fu_698_p3;
    Cluster_1_Phi32_0_Cl_fu_698_p3 <= 
        p_read38_read_fu_498_p3 when (tmp_3_fu_660_p2(0) = '1') else 
        p_read36_read_fu_382_p3;
    Cluster_1_Phi32_1_Cl_fu_1084_p3 <= 
        Cluster_1_Phi_0_Clus_fu_706_p3 when (tmp_48_1_fu_1038_p2(0) = '1') else 
        Cluster_1_Phi31_0_Cl_fu_760_p3;
    Cluster_1_Phi33_0_Cl_fu_752_p3 <= 
        p_read39_read_fu_556_p3 when (tmp_4_fu_714_p2(0) = '1') else 
        p_read37_read_fu_440_p3;
    Cluster_1_Phi33_1_Cl_fu_1076_p3 <= 
        Cluster_1_Phi31_0_Cl_fu_760_p3 when (tmp_48_1_fu_1038_p2(0) = '1') else 
        Cluster_1_Phi_0_Clus_fu_706_p3;
    Cluster_1_Phi34_0_Cl_fu_814_p3 <= 
        p_read32_read_fu_390_p3 when (tmp_28_1_fu_768_p2(0) = '1') else 
        p_read34_read_fu_506_p3;
    Cluster_1_Phi34_1_Cl_fu_1138_p3 <= 
        Cluster_1_Phi36_0_Cl_fu_806_p3 when (tmp_48_2_fu_1092_p2(0) = '1') else 
        Cluster_1_Phi3744_0_s_fu_860_p3;
    Cluster_1_Phi35_0_Cl_fu_868_p3 <= 
        p_read33_read_fu_448_p3 when (tmp_33_1_fu_822_p2(0) = '1') else 
        p_read35_read_fu_564_p3;
    Cluster_1_Phi35_1_Cl_fu_1130_p3 <= 
        Cluster_1_Phi3744_0_s_fu_860_p3 when (tmp_48_2_fu_1092_p2(0) = '1') else 
        Cluster_1_Phi36_0_Cl_fu_806_p3;
    Cluster_1_Phi36_0_Cl_fu_806_p3 <= 
        p_read34_read_fu_506_p3 when (tmp_28_1_fu_768_p2(0) = '1') else 
        p_read32_read_fu_390_p3;
    Cluster_1_Phi36_1_Cl_fu_1192_p3 <= 
        Cluster_1_Phi34_0_Cl_fu_814_p3 when (tmp_48_3_fu_1146_p2(0) = '1') else 
        Cluster_1_Phi35_0_Cl_fu_868_p3;
    Cluster_1_Phi3744_0_s_fu_860_p3 <= 
        p_read35_read_fu_564_p3 when (tmp_33_1_fu_822_p2(0) = '1') else 
        p_read33_read_fu_448_p3;
    Cluster_1_Phi3744_1_s_fu_1184_p3 <= 
        Cluster_1_Phi35_0_Cl_fu_868_p3 when (tmp_48_3_fu_1146_p2(0) = '1') else 
        Cluster_1_Phi34_0_Cl_fu_814_p3;
    Cluster_1_Phi42_0_Cl_fu_922_p3 <= 
        p_read1_fu_586_p3 when (tmp_38_1_fu_876_p2(0) = '1') else 
        p_read5_fu_630_p3;
    Cluster_1_Phi42_1_Cl_fu_1246_p3 <= 
        Cluster_1_Phi44_0_Cl_fu_914_p3 when (tmp_53_2_fu_1200_p2(0) = '1') else 
        Cluster_1_Phi45_0_Cl_fu_968_p3;
    Cluster_1_Phi43_0_Cl_fu_976_p3 <= 
        p_read3_fu_608_p3 when (tmp_43_1_fu_930_p2(0) = '1') else 
        p_read7_fu_652_p3;
    Cluster_1_Phi43_1_Cl_fu_1238_p3 <= 
        Cluster_1_Phi45_0_Cl_fu_968_p3 when (tmp_53_2_fu_1200_p2(0) = '1') else 
        Cluster_1_Phi44_0_Cl_fu_914_p3;
    Cluster_1_Phi44_0_Cl_fu_914_p3 <= 
        p_read5_fu_630_p3 when (tmp_38_1_fu_876_p2(0) = '1') else 
        p_read1_fu_586_p3;
    Cluster_1_Phi44_1_Cl_fu_1300_p3 <= 
        Cluster_1_Phi42_0_Cl_fu_922_p3 when (tmp_53_3_fu_1254_p2(0) = '1') else 
        Cluster_1_Phi43_0_Cl_fu_976_p3;
    Cluster_1_Phi45_0_Cl_fu_968_p3 <= 
        p_read7_fu_652_p3 when (tmp_43_1_fu_930_p2(0) = '1') else 
        p_read3_fu_608_p3;
    Cluster_1_Phi45_1_Cl_fu_1292_p3 <= 
        Cluster_1_Phi43_0_Cl_fu_976_p3 when (tmp_53_3_fu_1254_p2(0) = '1') else 
        Cluster_1_Phi42_0_Cl_fu_922_p3;
    Cluster_1_Phi_0_Clus_fu_706_p3 <= 
        p_read36_read_fu_382_p3 when (tmp_3_fu_660_p2(0) = '1') else 
        p_read38_read_fu_498_p3;
    Cluster_1_Phi_0_rea_1_fu_378_p1 <= std_logic_vector(resize(unsigned(Cluster_1_Phi_0_rea),2));
    Cluster_1_Phi_1_Clus_fu_1030_p3 <= 
        Cluster_1_Phi32_0_Cl_fu_698_p3 when (tmp_5_fu_984_p2(0) = '1') else 
        Cluster_1_Phi33_0_Cl_fu_752_p3;
    Cluster_1_Phi_1_rea_1_fu_436_p1 <= std_logic_vector(resize(unsigned(Cluster_1_Phi_1_rea),2));
    Cluster_1_Phi_2_rea_1_fu_494_p1 <= std_logic_vector(resize(unsigned(Cluster_1_Phi_2_rea),2));
    Cluster_1_Phi_3_rea_1_fu_552_p1 <= std_logic_vector(resize(unsigned(Cluster_1_Phi_3_rea),2));
    ap_CS_fsm_state1 <= ap_CS_fsm(0 downto 0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1 downto 1);

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce, ap_CS_fsm_state2)
    begin
        if ((((ap_const_logic_0 = ap_start) and (ap_CS_fsm_state1 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_ce) and (ap_const_lv1_1 = ap_CS_fsm_state2)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_0 = ap_start) and (ap_CS_fsm_state1 = ap_const_lv1_1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_ce, ap_CS_fsm_state2)
    begin
        if (((ap_const_logic_1 = ap_ce) and (ap_const_lv1_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    ap_return_0 <= call_ret_bitonic_1_16_fu_300_ap_return_0;
    ap_return_1 <= call_ret_bitonic_1_16_fu_300_ap_return_1;
    ap_return_2 <= call_ret_bitonic_1_16_fu_300_ap_return_2;
    ap_return_3 <= call_ret_bitonic_1_16_fu_300_ap_return_3;
    ap_return_4 <= call_ret_bitonic_1_16_fu_300_ap_return_4;
    ap_return_5 <= call_ret_bitonic_1_16_fu_300_ap_return_5;
    ap_return_6 <= call_ret_bitonic_1_16_fu_300_ap_return_6;
    ap_return_7 <= call_ret_bitonic_1_16_fu_300_ap_return_7;
    ap_return_8 <= call_ret_bitonic_1_16_fu_300_ap_return_8;
    ap_return_9 <= call_ret_bitonic_1_16_fu_300_ap_return_9;
    p_read16_read_fu_370_p3 <= 
        Cluster_1_Eta_0_rea when (tmp_s_fu_340_p2(0) = '1') else 
        Cluster_1_Eta_4_rea;
    p_read17_read_fu_428_p3 <= 
        Cluster_1_Eta_1_rea when (tmp_19_1_fu_398_p2(0) = '1') else 
        Cluster_1_Eta_5_rea;
    p_read18_read_fu_486_p3 <= 
        Cluster_1_Eta_2_rea when (tmp_19_2_fu_456_p2(0) = '1') else 
        Cluster_1_Eta_6_rea;
    p_read19_read_fu_544_p3 <= 
        Cluster_1_Eta_3_rea when (tmp_19_3_fu_514_p2(0) = '1') else 
        Cluster_1_Eta_7_rea;
    p_read1_fu_586_p3 <= 
        ap_const_lv2_0 when (tmp_2_fu_572_p2(0) = '1') else 
        Cluster_1_Phi_8_rea;
    p_read1_read5_fu_412_p3 <= 
        Cluster_1_Deposits_1 when (tmp_19_1_fu_398_p2(0) = '1') else 
        Cluster_1_Deposits_5;
    p_read20_read_fu_362_p3 <= 
        Cluster_1_Eta_4_rea when (tmp_s_fu_340_p2(0) = '1') else 
        Cluster_1_Eta_0_rea;
    p_read21_read_fu_420_p3 <= 
        Cluster_1_Eta_5_rea when (tmp_19_1_fu_398_p2(0) = '1') else 
        Cluster_1_Eta_1_rea;
    p_read22_read_fu_478_p3 <= 
        Cluster_1_Eta_6_rea when (tmp_19_2_fu_456_p2(0) = '1') else 
        Cluster_1_Eta_2_rea;
    p_read23_read_fu_536_p3 <= 
        Cluster_1_Eta_7_rea when (tmp_19_3_fu_514_p2(0) = '1') else 
        Cluster_1_Eta_3_rea;
    p_read2_fu_600_p3 <= 
        ap_const_lv2_0 when (tmp_23_1_fu_594_p2(0) = '1') else 
        Cluster_1_Eta_9_rea;
    p_read2_read6_fu_470_p3 <= 
        Cluster_1_Deposits_2 when (tmp_19_2_fu_456_p2(0) = '1') else 
        Cluster_1_Deposits_6;
    p_read32_read_fu_390_p3 <= 
        Cluster_1_Phi_0_rea_1_fu_378_p1 when (tmp_s_fu_340_p2(0) = '1') else 
        Cluster_1_Phi_4_rea;
    p_read33_read_fu_448_p3 <= 
        Cluster_1_Phi_1_rea_1_fu_436_p1 when (tmp_19_1_fu_398_p2(0) = '1') else 
        Cluster_1_Phi_5_rea;
    p_read34_read_fu_506_p3 <= 
        Cluster_1_Phi_2_rea_1_fu_494_p1 when (tmp_19_2_fu_456_p2(0) = '1') else 
        Cluster_1_Phi_6_rea;
    p_read35_read_fu_564_p3 <= 
        Cluster_1_Phi_3_rea_1_fu_552_p1 when (tmp_19_3_fu_514_p2(0) = '1') else 
        Cluster_1_Phi_7_rea;
    p_read36_read_fu_382_p3 <= 
        Cluster_1_Phi_4_rea when (tmp_s_fu_340_p2(0) = '1') else 
        Cluster_1_Phi_0_rea_1_fu_378_p1;
    p_read37_read_fu_440_p3 <= 
        Cluster_1_Phi_5_rea when (tmp_19_1_fu_398_p2(0) = '1') else 
        Cluster_1_Phi_1_rea_1_fu_436_p1;
    p_read38_read_fu_498_p3 <= 
        Cluster_1_Phi_6_rea when (tmp_19_2_fu_456_p2(0) = '1') else 
        Cluster_1_Phi_2_rea_1_fu_494_p1;
    p_read39_read_fu_556_p3 <= 
        Cluster_1_Phi_7_rea when (tmp_19_3_fu_514_p2(0) = '1') else 
        Cluster_1_Phi_3_rea_1_fu_552_p1;
    p_read3_fu_608_p3 <= 
        ap_const_lv2_0 when (tmp_23_1_fu_594_p2(0) = '1') else 
        Cluster_1_Phi_9_rea;
    p_read3_read7_fu_528_p3 <= 
        Cluster_1_Deposits_3 when (tmp_19_3_fu_514_p2(0) = '1') else 
        Cluster_1_Deposits_7;
    p_read4_fu_622_p3 <= 
        ap_const_lv2_0 when (tmp_23_2_fu_616_p2(0) = '1') else 
        Cluster_1_Eta_10_re;
    p_read4_read_fu_346_p3 <= 
        Cluster_1_Deposits_4 when (tmp_s_fu_340_p2(0) = '1') else 
        Cluster_1_Deposits_0;
    p_read5_fu_630_p3 <= 
        ap_const_lv2_0 when (tmp_23_2_fu_616_p2(0) = '1') else 
        Cluster_1_Phi_10_re;
    p_read5_read1_fu_404_p3 <= 
        Cluster_1_Deposits_5 when (tmp_19_1_fu_398_p2(0) = '1') else 
        Cluster_1_Deposits_1;
    p_read6_fu_644_p3 <= 
        ap_const_lv2_0 when (tmp_23_3_fu_638_p2(0) = '1') else 
        Cluster_1_Eta_11_re;
    p_read6_read2_fu_462_p3 <= 
        Cluster_1_Deposits_6 when (tmp_19_2_fu_456_p2(0) = '1') else 
        Cluster_1_Deposits_2;
    p_read7_fu_652_p3 <= 
        ap_const_lv2_0 when (tmp_23_3_fu_638_p2(0) = '1') else 
        Cluster_1_Phi_11_re;
    p_read7_read3_fu_520_p3 <= 
        Cluster_1_Deposits_7 when (tmp_19_3_fu_514_p2(0) = '1') else 
        Cluster_1_Deposits_3;
    p_read_fu_578_p3 <= 
        ap_const_lv2_0 when (tmp_2_fu_572_p2(0) = '1') else 
        Cluster_1_Eta_8_rea;
    p_read_read4_fu_354_p3 <= 
        Cluster_1_Deposits_0 when (tmp_s_fu_340_p2(0) = '1') else 
        Cluster_1_Deposits_4;
    tmp_19_1_fu_398_p2 <= "1" when (unsigned(Cluster_1_Deposits_1) < unsigned(Cluster_1_Deposits_5)) else "0";
    tmp_19_2_fu_456_p2 <= "1" when (unsigned(Cluster_1_Deposits_2) < unsigned(Cluster_1_Deposits_6)) else "0";
    tmp_19_3_fu_514_p2 <= "1" when (unsigned(Cluster_1_Deposits_3) < unsigned(Cluster_1_Deposits_7)) else "0";
    tmp_23_1_fu_594_p2 <= "1" when (Cluster_1_Deposits_9 = ap_const_lv16_0) else "0";
    tmp_23_2_fu_616_p2 <= "1" when (Cluster_1_Deposits_1_3 = ap_const_lv16_0) else "0";
    tmp_23_3_fu_638_p2 <= "1" when (Cluster_1_Deposits_1_4 = ap_const_lv16_0) else "0";
    tmp_28_1_fu_768_p2 <= "1" when (unsigned(p_read_read4_fu_354_p3) < unsigned(p_read2_read6_fu_470_p3)) else "0";
    tmp_2_fu_572_p2 <= "1" when (Cluster_1_Deposits_8 = ap_const_lv16_0) else "0";
    tmp_33_1_fu_822_p2 <= "1" when (unsigned(p_read1_read5_fu_412_p3) < unsigned(p_read3_read7_fu_528_p3)) else "0";
    tmp_38_1_fu_876_p2 <= "1" when (unsigned(Cluster_1_Deposits_8) > unsigned(Cluster_1_Deposits_1_3)) else "0";
    tmp_3_fu_660_p2 <= "1" when (unsigned(p_read4_read_fu_346_p3) < unsigned(p_read6_read2_fu_462_p3)) else "0";
    tmp_43_1_fu_930_p2 <= "1" when (unsigned(Cluster_1_Deposits_9) > unsigned(Cluster_1_Deposits_1_4)) else "0";
    tmp_48_1_fu_1038_p2 <= "1" when (unsigned(Cluster_1_Deposits_fu_674_p3) < unsigned(Cluster_1_Deposits1_fu_728_p3)) else "0";
    tmp_48_2_fu_1092_p2 <= "1" when (unsigned(Cluster_1_Deposits6_s_fu_774_p3) < unsigned(Cluster_1_Deposits7_s_fu_828_p3)) else "0";
    tmp_48_3_fu_1146_p2 <= "1" when (unsigned(Cluster_1_Deposits4_s_fu_782_p3) < unsigned(Cluster_1_Deposits5_s_fu_836_p3)) else "0";
    tmp_4_fu_714_p2 <= "1" when (unsigned(p_read5_read1_fu_404_p3) < unsigned(p_read7_read3_fu_520_p3)) else "0";
    tmp_53_2_fu_1200_p2 <= "1" when (unsigned(Cluster_1_Deposits2_fu_882_p3) > unsigned(Cluster_1_Deposits3_fu_936_p3)) else "0";
    tmp_53_3_fu_1254_p2 <= "1" when (unsigned(Cluster_1_Deposits12_1_fu_890_p3) > unsigned(Cluster_1_Deposits4_fu_944_p3)) else "0";
    tmp_5_fu_984_p2 <= "1" when (unsigned(Cluster_1_Deposits2_s_fu_666_p3) < unsigned(Cluster_1_Deposits3_s_fu_720_p3)) else "0";
    tmp_s_fu_340_p2 <= "1" when (unsigned(Cluster_1_Deposits_0) < unsigned(Cluster_1_Deposits_4)) else "0";
end behav;
